'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom'),{createOverviewService}=require('../src/overview-service');
const html=fs.readFileSync(path.join(__dirname,'../overview.html'),'utf8'),script=fs.readFileSync(path.join(__dirname,'../overview.js'),'utf8');
function raw(now){return{sessionId:'real-parent',source:'codex',codexLifecycle:1,codexTurnId:'current-turn',codexClosedTurn:false,codexHookAt:new Date(now).toISOString(),cwd:path.resolve('/project'),signal:'tool-use',codexAgents:[{id:'native-child',status:'working',since:new Date(now).toISOString()}],codexSelfReports:[{id:'declared-child',name:'Overview UI author',taskTitle:'Build <img src=x onerror=private()> actual names',status:'working',parentTurnId:'current-turn',observedAt:now,source:'self-reported'}]};}
async function render(value){const dom=new JSDOM(html,{runScripts:'outside-only',pretendToBeVisual:true});dom.window.overviewApi={state:async()=>value};dom.window.eval(script);await new Promise(resolve=>setImmediate(resolve));return dom;}
test('actual backend DTO renders explicit agent name/task/provenance as inert text beside unchanged provider roster',async()=>{const now=Date.now(),svc=createOverviewService({sessions:()=>[raw(now)],now:()=>now}),snapshot=await svc.snapshot(),dom=await render(snapshot);try{const children=dom.window.document.querySelectorAll('li.agent');assert.equal(children.length,2);assert.match(children[1].textContent,/Overview UI author/);assert.match(children[1].textContent,/Build <img/);assert.match(children[1].textContent,/Self-reported activity/);assert.match(children[0].textContent,/Reported activity/);assert.equal(dom.window.document.querySelectorAll('#content img').length,0);assert.equal(children[1].querySelectorAll('button:disabled').length,2);}finally{dom.window.close();}});
test('silent declared Working becomes visibly stale despite a fresh provider parent hook',async()=>{const now=Date.now(),parent=raw(now);parent.codexSelfReports[0].observedAt=now-90001;const dom=await render(await createOverviewService({sessions:()=>[parent],now:()=>now}).snapshot());try{const child=dom.window.document.querySelectorAll('li.agent')[1];assert.match(child.textContent,/Working · Stale/);assert.match(child.textContent,/Self-reported activity/);assert.equal(child.querySelectorAll('button:disabled').length,2);}finally{dom.window.close();}});
for(const reporting of [{source:['self-reported'],observed_at:1},{source:'self-reported',observed_at:[1]},{source:'self-reported',observed_at:1,turn:'private'},{source:'provider-verified',observed_at:1}])test(`renderer refuses malformed provenance ${JSON.stringify(reporting)}`,async()=>{const now=Date.now(),snapshot=await createOverviewService({sessions:()=>[raw(now)],now:()=>now}).snapshot();snapshot.sessions[0].children[1].reporting=reporting;const dom=await render(snapshot);try{assert.equal(dom.window.document.querySelectorAll('article.session').length,0);assert.match(dom.window.document.body.textContent,/unavailable|could not|Refresh/i);}finally{dom.window.close();}});
