'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{EventEmitter}=require('node:events'),{pathToFileURL}=require('node:url'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'buddy-window/index.js'),'utf8'),bridge=fs.readFileSync(path.join(root,'overview-preload.js'),'utf8'),html=fs.readFileSync(path.join(root,'overview.html'),'utf8'),renderer=fs.readFileSync(path.join(root,'overview.js'),'utf8');
const tick=()=>new Promise(r=>setImmediate(r));
function mainFixture(){const DIR=path.join(root,'buddy-window'),expected=pathToFileURL(path.join(DIR,'..','overview.html')).href,sent=[];const wc=new EventEmitter();Object.assign(wc,{isDestroyed:()=>false,getURL:()=>expected,mainFrame:{url:expected},isLoading:()=>true,send:(...args)=>sent.push(args),loadFile:()=>Promise.resolve()});const v={webContents:wc};const win={isDestroyed:()=>false,contentView:{children:[]}};const c={win,selected:'overview',content:null,localViews:new Map(),DIR,path,pathToFileURL,WebContentsView:class{constructor(){return v;}},nativeTheme:{shouldUseDarkColors:false},lockLocal:()=>{},retireSetupDocument:()=>{},onLocalPage:()=>{},attach:view=>{c.content=view;win.contentView.children=[view];}};v.setBackgroundColor=()=>{};vm.createContext(c);const start=source.indexOf('  function notifyOverviewReady(v) {'),end=source.indexOf('  // Local pages load',start);vm.runInContext(source.slice(start,end),c);return{c,v,wc,win,sent,page:{id:'overview',file:'overview.html',preload:'overview-preload.js'}};}
test('actual local factory waits for completed exact initial load then sends readiness without payload',()=>{const x=mainFixture();x.c.showLocal(x.page);assert.deepEqual(x.sent,[]);x.wc.isLoading=()=>false;x.wc.emit('did-finish-load');assert.deepEqual(x.sent,[['overview:ready']]);});
test('cached attached Overview emits ready without another load event',()=>{const x=mainFixture();x.c.showLocal(x.page);x.wc.isLoading=()=>false;x.c.showLocal(x.page);assert.deepEqual(x.sent,[['overview:ready']]);});
for(const [name,mutate]of [['closed window',x=>x.win.isDestroyed=()=>true],['destroyed page',x=>x.wc.isDestroyed=()=>true],['other selected',x=>x.c.selected='board'],['detached content',x=>x.c.content={}],['detached view',x=>x.win.contentView.children=[]],['replaced registry view',x=>x.c.localViews.set('overview',{})],['foreign URL',x=>x.wc.getURL=()=> 'https://foreign.invalid/'],['foreign frame',x=>x.wc.mainFrame.url='https://foreign.invalid/'],['still loading',x=>x.wc.isLoading=()=>true]])test('completed load refuses readiness for '+name,()=>{const x=mainFixture();x.c.showLocal(x.page);x.wc.isLoading=()=>false;mutate(x);x.wc.emit('did-finish-load');assert.deepEqual(x.sent,[]);});
test('normal other local page does not emit Overview readiness',()=>{const x=mainFixture();x.c.selected='settings';x.c.showLocal({...x.page,id:'settings'});x.wc.isLoading=()=>false;x.wc.emit('did-finish-load');assert.deepEqual(x.sent,[]);});
function viewFixture(state){const dom=new JSDOM(html,{runScripts:'outside-only',url:'file:///synthetic/overview.html'}),intervals=[];let ready,hidden=false;Object.defineProperty(dom.window.document,'hidden',{get:()=>hidden});dom.window.overviewApi={state,onReady:callback=>{ready=callback;return()=>{};},open:async()=>({ok:false}),message:async()=>({ok:false})};dom.window.setInterval=callback=>intervals.push(callback);dom.window.eval(renderer);return{dom,document:dom.window.document,intervals,ready:()=>ready(),hide:value=>{hidden=value;dom.window.document.dispatchEvent(new dom.window.Event('visibilitychange'));},close:()=>dom.window.close()};}
const dto=()=>({schema:1,status:'complete',observed_at:Date.now(),omitted:0,sessions:[]});
test('real renderer makes no premature load read or unavailable flash, then refreshes immediately on ready',async()=>{let calls=0;const x=viewFixture(async()=>{calls++;return dto();});try{assert.equal(calls,0);x.intervals[0]();assert.equal(calls,0);assert.doesNotMatch(x.document.body.textContent,/Activity unavailable/);x.ready();await tick();assert.equal(calls,1);assert.match(x.document.body.textContent,/No activity reported yet/);assert.doesNotMatch(x.document.body.textContent,/Activity unavailable/);}finally{x.close();}});
test('ready while hidden makes no read and visible transition reads immediately',async()=>{let calls=0;const x=viewFixture(async()=>{calls++;return dto();});try{x.hide(true);x.ready();await tick();assert.equal(calls,0);x.hide(false);await tick();assert.equal(calls,1);}finally{x.close();}});
test('repeated ready refresh generations withhold an older report',async()=>{const reads=[];const x=viewFixture(()=>new Promise(r=>reads.push(r)));try{x.ready();x.ready();reads[1](dto());await tick();reads[0]({...dto(),status:'unavailable'});await tick();assert.match(x.document.body.textContent,/No activity reported yet/);assert.doesNotMatch(x.document.body.textContent,/Activity unavailable/);}finally{x.close();}});
test('real post-ready unavailable read stays truthful',async()=>{const x=viewFixture(async()=>null);try{x.ready();await tick();assert.match(x.document.body.textContent,/Activity unavailable/);}finally{x.close();}});
test('closed preload ready channel exposes no event/payload and unsubscribe removes only owned listener',()=>{let api,calls=0,args,listener,removed;vm.runInNewContext(bridge,{Buffer,Promise,require:()=>({contextBridge:{exposeInMainWorld:(_name,value)=>api=value},ipcRenderer:{invoke:()=>Promise.resolve(),on:(name,fn)=>{assert.equal(name,'overview:ready');listener=fn;},removeListener:(name,fn)=>removed=[name,fn]}})});const off=api.onReady((...a)=>{calls++;args=a;});listener({private:'sentinel'},'forged');assert.equal(calls,0);listener({private:'sentinel'});assert.equal(calls,1);assert.deepEqual(args,[]);off();assert.equal(removed[0],'overview:ready');assert.equal(removed[1],listener);});
test('preload ignores invalid ready callback without registering anything',()=>{let api,registrations=0;vm.runInNewContext(bridge,{Buffer,Promise,require:()=>({contextBridge:{exposeInMainWorld:(_name,value)=>api=value},ipcRenderer:{on:()=>registrations++}})});assert.equal(typeof api.onReady(null),'function');assert.equal(registrations,0);});

test('finish while loading stays withheld, then stopped-loading triggers guarded immediate readiness',()=>{const x=mainFixture();x.c.showLocal(x.page);x.wc.emit('did-finish-load');assert.deepEqual(x.sent,[]);x.wc.isLoading=()=>false;x.wc.emit('did-stop-loading');assert.deepEqual(x.sent,[['overview:ready']]);});
for(const [name,mutate]of [['foreign-document',x=>x.wc.getURL=()=> 'https://foreign.invalid/'],['inactive-page',x=>x.c.selected='board'],['detached-view',x=>x.win.contentView.children=[]],['still-loading',x=>x.wc.isLoading=()=>true]])test('stopped-loading '+name+' cannot manufacture readiness',()=>{const x=mainFixture();x.c.showLocal(x.page);x.wc.emit('did-finish-load');x.wc.isLoading=()=>false;mutate(x);x.wc.emit('did-stop-loading');assert.deepEqual(x.sent,[]);});
