'use strict';
// All mutation tests use explicitly synthetic inert temp profiles. No Codex
// binary, provider account, model, CLI or production native writer is invoked.
const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs'), os = require('node:os'), path = require('node:path'), crypto = require('node:crypto');
const V = require('../src/plugins/index-verify'), T = require('../src/plugins/toml-owned'), J = require('../src/plugins/journal-codec'), A = require('../src/plugins/native-adapter-contract');
const { createPluginPlanner, REQUIRED_COMMANDS } = require('../src/plugins/plan'), { createPluginTransactions } = require('../src/plugins/transactions');
const NOW = Date.parse('2026-10-02T12:00:00.000Z'), clone = x => JSON.parse(V.canonical(x));
function fixture(t, { mcp = false } = {}) {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'plugins-kernel-synthetic-'))); t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const bundle = path.join(dir, 'bundle'), root = path.join(bundle, 'delivery-review'), profile = path.join(dir, 'profile'), cache = path.join(profile, 'cache'), config = path.join(profile, 'config.toml'), binary = path.join(dir, 'synthetic-codex');
  fs.mkdirSync(path.join(root, 'skills/delivery-review'), { recursive: true }); fs.mkdirSync(cache, { recursive: true }); fs.writeFileSync(binary, 'Never executed synthetic binary.'); fs.writeFileSync(config, '# Human fixture notes\r\nmodel = "fixture-model"\r\n[foreign]\r\nprivate_value = "synthetic-private-data"\r\n');
  const pair = crypto.generateKeyPairSync('ed25519'), keyId = V.keyId(pair.publicKey), catalog = Buffer.from('{"entries":[{"id":"skill:delivery-review"}]}');
  let time = NOW, current = true, actor = 1, clock = 0, holds = null, wrappingCalls = 0, beginCalls = 0, approvals = [];
  const host = { kind: 'codex', version: '0.159.2', binary_path: binary, binary_sha256: V.hash(fs.readFileSync(binary)), binary_stat: 'synthetic-binary:1', commands: [...REQUIRED_COMMANDS].sort() }, account = () => ({ user_id: 'u1', team_id: 't1', member_id: 'm1', device_id: 'd1', generation: actor });
  let descriptor; function source(version) {
    const texts = new Map([['plugin.json', JSON.stringify({ $schema: 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json', name: 'delivery-review', version, description: 'Synthetic inert skill.' })], ['skills/delivery-review/SKILL.md', `---\nname: delivery-review\ndescription: Synthetic review\n---\nReview exact evidence for version ${version}.\n`]]);
    if (mcp) texts.set('mcp.json', '{"mcpServers":{"docs":{"url":"https://docs.example.com/mcp"}}}');
    for (const [name, value] of texts) fs.writeFileSync(path.join(root, name), value);
    const files = [...texts].map(([name, value]) => ({ path: name, bytes: Buffer.byteLength(value), sha256: V.hash(value) }));
    descriptor = { id: 'delivery-review', catalog_id: 'skill:delivery-review', name: 'delivery-review', version, host_min: '0.159.2', source: { type: 'bundled-directory', path: 'delivery-review', attribution: 'Synthetic curated source' }, files, package_sha256: V.packageHash(files), components: { manifest: 'plugin.json', skills: ['skills/delivery-review/SKILL.md'], mcp: mcp ? ['mcp.json'] : [] }, capabilities: mcp ? ['instructions', 'network', 'oauth', 'remote-mcp'] : ['instructions'] };
  } source('1.0.0');
  const ledger = new Map(), journals = new Map(), staged = new Map(), calls = [];
  const bytesOfCache = () => [...ledger].map(([id, m]) => ({ id, files: m.descriptor.files.map(f => ({ path: f.path, hash: fs.existsSync(path.join(cache, id, f.path)) ? V.hash(fs.readFileSync(path.join(cache, id, f.path))) : null })) }));
  const snapshot = () => ({ profile_root: profile, config: { sha256: V.hash(fs.readFileSync(config)), stat: 'fixture-config:' + V.hash(fs.readFileSync(config)) }, cache: { sha256: V.hash(bytesOfCache()), stat: 'fixture-cache:' + V.hash(bytesOfCache()) }, host, account: account(), current: () => current });
  function planner() { return createPluginPlanner({ snapshot: () => { const value = snapshot(); if (f.mutateSnapshot) f.mutateSnapshot(value); return value; }, bundleRoot: bundle, now: () => time, loadCatalog: async () => catalog, loadIndex: async () => { const bytes = Buffer.from(JSON.stringify({ schemaVersion: 1, generatedAt: '2026-10-02T11:00:00.000Z', catalog_sha256: V.hash(catalog), entries: [descriptor] })); return { bytes, signature: JSON.stringify({ alg: 'ed25519', keyId, sig: crypto.sign(null, bytes, pair.privateKey).toString('base64') }) }; }, verifyIndex: (bytes, signature) => { const value = V.createIndexVerifier({ keys: [{ keyId, key: pair.publicKey }], now: () => time })(bytes, signature); if (f.mutateVerified) f.mutateVerified(value); return value; } }); }
  const idOf = m => `${m.descriptor.name}@${m.marketplace}`;
  function inspect(m) {
    const id = idOf(m), exists = ledger.has(id), configState = T.owned(fs.readFileSync(config), id), files = m.descriptor.files.map(f => ({ path: f.path, bytes: fs.existsSync(path.join(cache, id, f.path)) ? fs.readFileSync(path.join(cache, id, f.path)) : null }));
    const actual = files.map(f => ({ path: f.path, bytes: f.bytes?.length ?? 0, sha256: f.bytes ? V.hash(f.bytes) : '0'.repeat(64) })), exact = exists && V.packageHash(actual) === m.descriptor.package_sha256 && configState.exists;
    const value = { status: !exists ? 'missing' : exact ? 'exact' : 'changed', package_hash: V.packageHash(actual), cache_hash: V.hash(actual), config_enabled: configState.enabled ?? false, foreign_hash: configState.foreign_hash, receipt_hash: '', owned: exists, live_dependents: f.liveDependents ?? 0 };
    value.receipt_hash = V.hash({ ...value, receipt_hash: '' }); return value;
  }
  function inventory() { const value = { items: [...ledger.values()].map(m => ({ metadata: clone(m), inspection: inspect(m) })), receipt_hash: '' }; value.receipt_hash = V.hash(value); return value; }
  function files(m) { return new Map(m.descriptor.files.map(file => [file.path, fs.readFileSync(path.join(cache, idOf(m), file.path))])); }
  function writeFiles(m, content) { const dest = path.join(cache, idOf(m)); fs.rmSync(dest, { recursive: true, force: true }); for (const [name, bytes] of content) { fs.mkdirSync(path.dirname(path.join(dest, name)), { recursive: true }); fs.writeFileSync(path.join(dest, name), bytes); } ledger.set(idOf(m), clone(m)); }
  function remove(m) { fs.rmSync(path.join(cache, idOf(m)), { recursive: true, force: true }); ledger.delete(idOf(m)); }
  const wrapKey = crypto.randomBytes(32), wrapping = { available() { wrappingCalls++; return f.wrapAvailable !== false; }, async wrap(key) { const nonce = crypto.randomBytes(12), cipher = crypto.createCipheriv('aes-256-gcm', wrapKey, nonce); return Buffer.concat([nonce, cipher.update(key), cipher.final(), cipher.getAuthTag()]); }, async unwrap(bytes) { const cipher = crypto.createDecipheriv('aes-256-gcm', wrapKey, bytes.subarray(0, 12)); cipher.setAuthTag(bytes.subarray(-16)); return Buffer.concat([cipher.update(bytes.subarray(12, -16)), cipher.final()]); } };
  const receipts = new WeakSet();
  function action(kind, input, guard) {
    if (!guard()) throw new Error('fixture changed'); if (f.beforeNative) f.beforeNative(kind, input); if (!guard()) throw new Error('fixture changed');
    if (kind === 'inventory') return inventory();
    if (kind === 'inspect') return inspect(input.metadata);
    if (kind === 'journal-list') return { ids: [...journals.keys()] };
    if (kind === 'journal-create') { assert.equal(journals.has(input.id), false); journals.set(input.id, { header: Buffer.from(input.bytes), records: [] }); return { bytes_hash: V.hash(input.bytes) }; }
    if (kind === 'journal-append') { const j = journals.get(input.id); assert.equal(input.sequence, j.records.length + 1); assert.equal(input.expected_previous, V.hash(j.records.at(-1) ?? j.header)); j.records.push(Buffer.from(input.bytes)); return { bytes_hash: V.hash(input.bytes) }; }
    if (kind === 'journal-read') { const j = journals.get(input.id); if (!j) throw new Error('missing fixture'); return { header: Buffer.from(j.header), records: j.records.map(Buffer.from), census_hash: V.hash({ header: V.hash(j.header), records: j.records.map(V.hash) }) }; }
    if (kind === 'stage') { staged.set(input.id, { after: new Map(input.after.descriptor.files.map(file => [file.path, fs.readFileSync(path.join(input.source.root, file.path))])), before: input.before ? files(input.before) : null }); return { package_hash: input.after.descriptor.package_sha256, backup_hash: input.before?.descriptor.package_sha256 ?? null }; }
    if (kind === 'install-disabled') { assert.equal(input.expected_inventory, V.hash(inventory())); let bytes = fs.readFileSync(config); if (input.before) { assert.equal(inspect(input.before).status, 'exact'); bytes = T.replaceOwned(bytes, idOf(input.before), input.before.enabled, null); remove(input.before); } bytes = T.replaceOwned(bytes, idOf(input.after), null, false); writeFiles(input.after, staged.get(input.id).after); fs.writeFileSync(config, bytes); return { package_hash: input.after.descriptor.package_sha256, disabled: true }; }
    if (kind === 'restore') { assert.equal(input.expected_receipt, inspect(input.after).receipt_hash); let bytes = T.replaceOwned(fs.readFileSync(config), idOf(input.after), false, null); remove(input.after); if (input.before) { bytes = T.replaceOwned(bytes, idOf(input.before), null, input.before.enabled); writeFiles(input.before, staged.get(input.id).before); } fs.writeFileSync(config, bytes); return { restored: true, retained_marketplace: input.retain_marketplace }; }
    throw new Error('unsupported fixture operation');
  }
  const adapter = A.createNativePluginAdapter({ fixture: true, wrapping, attest: () => ({ kind: 'synthetic-plugin-fixture', protocol: 1, helper_hash: V.hash('fixture-only'), roots_hash: V.hash(profile), current }), observe: () => ({ profile_root: profile, platform: 'darwin', os_user: 'synthetic-user', generation: actor, foreground: f.foreground !== false, host_hash: V.hash(host), account: f.offline ? null : account() }), begin({ kind, input }, guard) {
    beginCalls++; calls.push(kind); let exited = true, reapResolve; const reaped = new Promise(resolve => { reapResolve = resolve; });
    const result = Promise.resolve().then(() => { if (holds?.kind === kind) { exited = false; holds.release = () => { exited = true; holds = null; reapResolve(); }; } const payload = action(kind, input, guard), receipt_hash = ['inventory', 'inspect'].includes(kind) ? payload.receipt_hash : V.hash({ kind, input, payload }); const result = { receipt_hash, payload }; if (f.mutateResult) f.mutateResult(kind, result); receipts.add(result); return result; });
    if (!holds || holds.kind !== kind) reapResolve(); return { result, reaped, cancel() {}, exited: () => exited };
  }, verifyReceipt: (_kind, value) => receipts.has(value) });
  function controller(adapterChoice = adapter) { return createPluginTransactions({ planner: planner(), adapter: adapterChoice, now: () => time, clock: () => clock, confirm: async request => { approvals.push(request); if (f.onConfirm) await f.onConfirm(request); return f.deny ? { approved: false, plan_hash: request.plan_hash } : { approved: true, plan_hash: request.plan_hash }; } }); }
  const f = { dir, root, profile, cache, config, source, planner, controller, adapter, wrapping, journals, ledger, calls, approvals, get descriptor() { return descriptor; }, get wrapCalls() { return wrappingCalls; }, get beginCalls() { return beginCalls; }, advance: n => time += n, setClock: n => clock = n, changeActor: () => actor++, invalidateSource: () => fs.writeFileSync(path.join(root, 'skills/delivery-review/SKILL.md'), 'Changed source'), setCurrent: value => current = value, hold: kind => { holds = { kind }; return holds; }, inventory, inspect };
  t.after(() => wrapKey.fill(0)); return f;
}
async function apply(f, c = f.controller(), operation = 'install') { const p = await c.plan('delivery-review', { operation, scope: 'user' }); assert.equal(p.ok, true, JSON.stringify(p)); assert.equal(p.status, 'review_required'); assert.equal(p.fixture, true); const r = await c.apply(p.plan.handle, { plan_hash: p.plan.plan_hash, reviewed_files: true, reviewed_config: true }); return { c, p, r }; }

test('synthetic fixture: absent or unbranded native adapter denies every authority-bearing method without trust or crypto calls', async t => {
  const f = fixture(t); for (const absent of [null, {}, { observe() { throw new Error('forged'); } }]) { const c = f.controller(absent); for (const value of [await c.plan('delivery-review'), await c.apply('forged', {}), await c.listLocked(), await c.recover(crypto.randomUUID()), await c.undo('forged', {})]) assert.equal(value.status, 'unavailable'); } assert.equal(f.beginCalls, 0); assert.equal(f.wrapCalls, 0);
});
test('synthetic fixture: exact signed review → disabled Apply → fresh controller recovery → conditional Undo preserves original CRLF private bytes', async t => {
  const f = fixture(t), before = fs.readFileSync(f.config), { c, p, r } = await apply(f); assert.equal(r.status, 'verified', JSON.stringify(r)); assert.equal(r.disabled, true); assert.ok(p.plan.files.every(x => x.text && V.hash(x.text) === x.sha256)); assert.equal(p.plan.config_review.enabled, false);
  assert.equal((await c.apply(p.plan.handle, { plan_hash: p.plan.plan_hash, reviewed_files: true, reviewed_config: true })).status, 'unavailable');
  const fresh = f.controller(); const locked = await fresh.listLocked(); assert.equal(locked.status, 'locked'); const wrapBefore = f.wrapCalls; assert.equal((await fresh.listLocked()).ok, true); assert.equal(f.wrapCalls, wrapBefore);
  const recovery = await fresh.recover(r.transaction_id); assert.equal(recovery.status, 'inspected', JSON.stringify(recovery)); const undo = await fresh.undo(recovery.recovery.handle, { inspection_hash: recovery.recovery.inspection_hash }); assert.equal(undo.status, 'undone', JSON.stringify(undo)); assert.ok(fs.readFileSync(f.config).equals(before)); assert.equal(f.ledger.size, 0); assert.equal(f.journals.size, 1);
  assert.equal((await fresh.undo(recovery.recovery.handle, { inspection_hash: recovery.recovery.inspection_hash })).status, 'unavailable');
  const disk = Buffer.concat([f.journals.get(r.transaction_id).header, ...f.journals.get(r.transaction_id).records]).toString(); assert.equal(disk.includes('synthetic-private-data'), false); assert.equal(disk.includes('Review exact evidence'), false); assert.equal(disk.includes(f.profile), false);
});
test('synthetic fixture: exact preexisting package is unowned no-op and grants no new Apply or Undo', async t => { const f = fixture(t); assert.equal((await apply(f)).r.ok, true); const result = await f.controller().plan('delivery-review'); assert.equal(result.status, 'already_present'); assert.equal(result.undo_available, false); assert.equal(result.owned_by_this_transaction, false); assert.equal(f.journals.size, 1); });
test('synthetic fixture: explicit owned update Undo restores exact old inert package and current foreign human edits', async t => {
  const f = fixture(t); assert.equal((await apply(f)).r.ok, true); const oldHash = f.descriptor.package_sha256; f.source('2.0.0'); const { r } = await apply(f, f.controller(), 'update'); assert.equal(r.ok, true, JSON.stringify(r));
  const fresh = f.controller(), recovery = await fresh.recover(r.transaction_id); fs.appendFileSync(f.config, '\r\n[human_new]\r\nannotation = "keep current edit"\r\n'); const undo = await fresh.undo(recovery.recovery.handle, { inspection_hash: recovery.recovery.inspection_hash }); assert.equal(undo.ok, true, JSON.stringify(undo)); assert.ok(fs.readFileSync(f.config, 'utf8').includes('keep current edit')); assert.equal([...f.ledger.values()][0].descriptor.package_sha256, oldHash); assert.ok(fs.readFileSync(path.join(f.cache, [...f.ledger.keys()][0], 'skills/delivery-review/SKILL.md'), 'utf8').includes('version 1.0.0'));
});
for (const boundary of ['actor', 'source', 'config', 'denial', 'expiry']) test(`synthetic fixture: ${boundary} after native confirmation consumes handle and prevents every journal or target write`, async t => {
  const f = fixture(t), c = f.controller(), p = await c.plan('delivery-review'), before = fs.readFileSync(f.config); f.onConfirm = () => { if (boundary === 'actor') f.changeActor(); if (boundary === 'source') f.invalidateSource(); if (boundary === 'config') fs.appendFileSync(f.config, '# Fresh edit\r\n'); if (boundary === 'denial') f.deny = true; if (boundary === 'expiry') f.advance(600001); };
  const r = await c.apply(p.plan.handle, { plan_hash: p.plan.plan_hash, reviewed_files: true, reviewed_config: true }); assert.equal(r.status, 'unavailable'); assert.equal(f.journals.size, 0); assert.equal(f.ledger.size, 0); if (boundary !== 'config') assert.ok(fs.readFileSync(f.config).equals(before)); assert.equal((await c.apply(p.plan.handle, { plan_hash: p.plan.plan_hash, reviewed_files: true, reviewed_config: true })).status, 'unavailable');
});
test('synthetic fixture: incomplete code/config review cannot prompt or mutate', async t => { const f = fixture(t), c = f.controller(), p = await c.plan('delivery-review'); const r = await c.apply(p.plan.handle, { plan_hash: p.plan.plan_hash, reviewed_files: false, reviewed_config: true }); assert.equal(r.status, 'unavailable'); assert.equal(f.approvals.length, 0); assert.equal(f.journals.size, 0); });
test('synthetic fixture: unavailable OS wrapping refuses explicit Apply but ordinary signed plan and locked listing are key-free', async t => { const f = fixture(t); f.wrapAvailable = false; const c = f.controller(), p = await c.plan('delivery-review'); assert.equal(p.ok, true); assert.equal(p.plan.wrapping_status, 'uninspected'); assert.equal((await c.listLocked()).ok, true); assert.equal(f.wrapCalls, 0); assert.equal((await c.apply(p.plan.handle, { plan_hash: p.plan.plan_hash, reviewed_files: true, reviewed_config: true })).status, 'unavailable'); assert.equal(f.journals.size, 0); assert.equal(f.ledger.size, 0); });
test('synthetic fixture: URL-only remote MCP mutation held before any native inventory or crypto request', async t => { const f = fixture(t, { mcp: true }); assert.equal((await f.controller().plan('delivery-review')).status, 'unavailable'); assert.equal(f.beginCalls, 0); assert.equal(f.wrapCalls, 0); });
test('synthetic fixture: unobserved native exit withholds reply and gates another controller through invalidate and close', async t => { const f = fixture(t), c = f.controller(), hold = f.hold('inventory'); const r = await c.plan('delivery-review'); assert.equal(r.status, 'unavailable'); assert.equal(c.pendingReap, true); const begun = f.beginCalls; c.invalidate(); assert.equal((await f.controller().plan('delivery-review')).status, 'unavailable'); assert.equal(f.beginCalls, begun); c.close(); assert.equal(c.pendingReap, true); hold.release(); assert.equal(c.pendingReap, false); assert.equal((await f.controller().plan('delivery-review')).ok, true); });
test('synthetic fixture: actual native await invalidation retains exit gate and cannot renew while response is pending', async t => { const f = fixture(t), c = f.controller(), hold = f.hold('inventory'); f.beforeNative = kind => { if (kind === 'inventory') c.invalidate(); }; const r = await c.plan('delivery-review'); assert.equal(r.ok, false); assert.equal(c.pendingReap, true); const begun = f.beginCalls; assert.equal((await f.controller().listLocked()).ok, false); assert.equal(f.beginCalls, begun); hold.release(); assert.equal(c.pendingReap, false); });
test('synthetic fixture: changed owned cache after recovery refuses Undo and retains original encrypted evidence', async t => { const f = fixture(t), { r } = await apply(f), c = f.controller(), rec = await c.recover(r.transaction_id); const m = [...f.ledger.values()][0]; fs.appendFileSync(path.join(f.cache, `${m.descriptor.name}@${m.marketplace}`, 'skills/delivery-review/SKILL.md'), 'Human modification'); const records = f.journals.get(r.transaction_id).records.length; assert.equal((await c.undo(rec.recovery.handle, { inspection_hash: rec.recovery.inspection_hash })).status, 'needs_review'); assert.equal(f.journals.get(r.transaction_id).records.length, records); assert.equal(f.ledger.size, 1); });
test('synthetic fixture: live marketplace dependents require retention and unknown post-effect failure never invents rollback', async t => { const f = fixture(t), { r } = await apply(f), c = f.controller(), rec = await c.recover(r.transaction_id); f.liveDependents = 1; const u = await c.undo(rec.recovery.handle, { inspection_hash: rec.recovery.inspection_hash }); assert.equal(u.ok, true); assert.equal(u.retained_marketplace, true); const f2 = fixture(t); f2.beforeNative = kind => { if (kind === 'inspect') throw new Error('Synthetic interrupted inspection'); }; const result = await apply(f2); assert.equal(result.r.status, 'needs_review'); assert.equal(result.r.retained, true); assert.equal(f2.ledger.size, 1); assert.equal(f2.journals.size, 1); const locked = await f2.controller().listLocked(); assert.equal(locked.transactions[0].undo_available, false); assert.equal((await f2.controller().recover(result.r.transaction_id)).ok, false); });
test('synthetic fixture: concurrent Apply consumes one handle before queuing and cannot replay an install', async t => { const f = fixture(t), c = f.controller(), p = await c.plan('delivery-review'), request = { plan_hash: p.plan.plan_hash, reviewed_files: true, reviewed_config: true }; const results = await Promise.all([c.apply(p.plan.handle, request), c.apply(p.plan.handle, request)]); assert.equal(results.filter(x => x.status === 'verified').length, 1); assert.equal(results.filter(x => x.status === 'unavailable').length, 1); assert.equal(f.calls.filter(x => x === 'install-disabled').length, 1); assert.equal(f.journals.size, 1); });
test('synthetic fixture: private planner source handoff is one-use, frozen and rechecks exact source/config/actor after transfer', async t => { const f = fixture(t), planner = f.planner(), p = await planner.plan('delivery-review'), proof = await planner.takeForTransaction(p.plan.id); assert.ok(proof); assert.equal(Object.isFrozen(proof.descriptor.source), true); assert.equal(await planner.takeForTransaction(p.plan.id), null); assert.equal((await planner.check(p.plan.id)).ok, false); assert.equal(await proof.recheck(), true); fs.appendFileSync(f.config, '# Later foreign edit\r\n'); assert.equal(await proof.recheck(), false); });
test('synthetic fixture: automated deadline after a real native read cancels further work and does not extend for reap', async t => { const f = fixture(t), c = f.controller(); f.beforeNative = kind => { if (kind === 'inventory') f.setClock(60001); }; assert.equal((await c.plan('delivery-review')).ok, false); assert.equal(c.pendingReap, false); assert.equal(f.calls.length, 1); assert.equal(f.journals.size, 0); });
test('synthetic fixture: local OS owner recovery can be explicitly inspected while account is offline; foreground still required', async t => { const f = fixture(t), { r } = await apply(f); f.offline = true; const c = f.controller(), rec = await c.recover(r.transaction_id); assert.equal(rec.status, 'inspected'); f.foreground = false; assert.equal((await c.undo(rec.recovery.handle, { inspection_hash: rec.recovery.inspection_hash })).ok, false); assert.equal(f.ledger.size, 1); });
test('synthetic fixture: matching name from a foreign source or unsupported downgrade cannot be overwritten', async t => { const f = fixture(t); assert.equal((await apply(f)).r.ok, true); const m = [...f.ledger.values()][0]; m.descriptor.source.attribution = 'Foreign catalog source'; f.source('2.0.0'); assert.equal((await f.controller().plan('delivery-review', { operation: 'update', scope: 'user' })).ok, false); m.descriptor.source.attribution = 'Synthetic curated source'; f.source('0.9.0'); assert.equal((await f.controller().plan('delivery-review', { operation: 'update', scope: 'user' })).ok, false); assert.equal(f.journals.size, 1); });
test('synthetic fixture: recovery refuses authenticated valid but interrupted journal prefix and grants no automatic Undo', async t => { const f = fixture(t), { r } = await apply(f), j = f.journals.get(r.transaction_id); j.records = j.records.slice(0, 2); const result = await f.controller().recover(r.transaction_id); assert.equal(result.status, 'needs_review'); assert.equal(result.retained, true); assert.equal(result.recovery, undefined); assert.equal(f.ledger.size, 1); });
test('synthetic fixture: unresolved OS wrapping is bounded, blocks renewal through invalidation and never publishes a late journal', async t => { const f = fixture(t), c = f.controller(), p = await c.plan('delivery-review'), wrap = f.wrapping.wrap; let release; f.wrapping.wrap = key => { f.setClock(59999); return wrap(key).then(cipher => new Promise(resolve => { release = () => resolve(cipher); })); }; const result = await c.apply(p.plan.handle, { plan_hash: p.plan.plan_hash, reviewed_files: true, reviewed_config: true }); assert.equal(result.status, 'unavailable'); assert.equal(c.pendingReap, true); c.invalidate(); assert.equal((await f.controller().plan('delivery-review')).ok, false); assert.equal(f.journals.size, 0); release(); await new Promise(resolve => setImmediate(resolve)); assert.equal(c.pendingReap, false); assert.equal(f.journals.size, 0); assert.equal(f.ledger.size, 0); });
test('synthetic fixture: coerced recovery UUIDs refuse before confirmation, native read or wrapping', async t => { const f = fixture(t), c = f.controller(); const id = crypto.randomUUID(), poison = { toString() { throw new Error('must not coerce'); } }; for (const value of [[id], new String(id), poison, 123, null]) { assert.equal((await c.recover(value)).ok, false); assert.equal(f.approvals.length, 0); assert.equal(f.beginCalls, 0); assert.equal(f.wrapCalls, 0); } });
test('synthetic fixture: coerced native receipt and locked IDs refuse without granting local recovery', async t => { const f = fixture(t), c = f.controller(); f.mutateResult = (_kind, result) => result.receipt_hash = [result.receipt_hash]; assert.equal((await c.listLocked()).ok, false); assert.equal(f.wrapCalls, 0); f.mutateResult = (kind, result) => { if (kind === 'journal-list') result.payload.ids = [[crypto.randomUUID()]]; }; assert.equal((await c.listLocked()).ok, false); assert.equal(f.wrapCalls, 0); assert.equal(f.approvals.length, 0); });
test('synthetic fixture: coerced journal census refuses before unwrap or Undo grant', async t => { const f = fixture(t), { r } = await apply(f), c = f.controller(), beforeWrap = f.wrapCalls; f.mutateResult = (kind, result) => { if (kind === 'journal-read') result.payload.census_hash = [result.payload.census_hash]; }; assert.equal((await c.recover(r.transaction_id)).ok, false); assert.equal(f.wrapCalls, beforeWrap); assert.equal(f.ledger.size, 1); });
test('synthetic fixture: private one-use handoff rejects malformed current config/cache/binary/index primitive hashes', async t => { for (const field of ['config', 'cache', 'binary', 'index']) { const f = fixture(t); if (field === 'index') { let held; f.mutateVerified = value => { held ??= [value.index_hash]; value.index_hash = held; }; } else f.mutateSnapshot = value => { if (field === 'binary') value.host.binary_sha256 = [value.host.binary_sha256]; else value[field].sha256 = [value[field].sha256]; }; const planner = f.planner(), p = await planner.plan('delivery-review'); assert.equal(p.ok, true); assert.equal(await planner.takeForTransaction(p.plan.id), null); assert.equal(await planner.takeForTransaction(p.plan.id), null); assert.equal(f.beginCalls, 0); assert.equal(f.wrapCalls, 0); } });
