'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {fixture,deferred}=require('./helpers/setups-transactions');
const {CORE_LIMITS}=require('../src/borrow/transaction-core');
const {STORE_LIMITS,safeStorageWrapping}=require('../src/borrow/transaction-store');
const {profile}=require('../src/borrow/transaction-targets');
const {validatePayload}=require('../src/borrow/payload');
const yieldTurn=()=>new Promise(resolve=>setImmediate(resolve));

test('prepared text snapshots survive a fresh store/core without changing any target bytes',async t=>{
  const f=fixture(t),before=fs.readFileSync(f.filename),result=await f.prepare();assert.equal(result.ok,true);assert.equal(result.phase,'prepared');assert.equal(result.target_files_changed,false);assert.deepEqual(fs.readFileSync(f.filename),before);
  assert.equal(f.disk().length,4);for(const entry of f.disk())assert.equal(entry.bytes.includes(before),false);
  const other=f.makeStore(),data=other.read(result.transaction_id,profile(f.home,process.platform,String(process.getuid?.()??'windows-fixture')).id);
  assert.deepEqual(data.targets[0].before.bytes,before);assert.equal(data.targets[0].after.bytes.toString(),f.file.content);assert.match(data.manifest.plan_hash,/^[a-f0-9]{64}$/);data.close();assert.equal(data.targets[0].before.bytes.every(byte=>byte===0),true);
});
test('missing target plans and prepared journal do not create target parents',async t=>{
  const f=fixture(t,{before:null}),plan=await f.plan();assert.equal(plan.ready,true);assert.equal(plan.targets[0].exists,false);
  const receipt=await f.core.prepare(plan.handle,plan.plan_hash);assert.equal(receipt.ok,true);assert.equal(fs.existsSync(path.join(f.home,'.codex')),false);
});
test('JSON plan preserves foreign bytes and explicitly reports retained conflicts',async t=>{
  const before='{\r\n  "foreign" : [ 1, 2 ],\r\n  "theme" : "light"\r\n}\r\n';
  const f=fixture(t,{source:'claude-code',relative:'.claude/settings.json',format:'json',content:'{"theme":"dark","new":true}',before,mode:'merge'});
  const plan=await f.plan();assert.equal(plan.ready,true);assert.deepEqual(plan.targets[0].conflicts,['theme']);
  const receipt=await f.core.prepare(plan.handle,plan.plan_hash);assert.equal(receipt.ok,true);assert.equal(fs.readFileSync(f.filename,'utf8'),before);
  const after=f.state.dialogs[0].previews[0].after.content;assert.match(after,/"foreign" : \[ 1, 2 \]/);assert.match(after,/"theme" : "light"/);assert.equal(JSON.parse(after).new,true);
});
test('JSON filled values are escaped data, encrypted at rest and absent from previews and receipts',async t=>{
  const local='opaque local value "quoted"\\tail';
  const f=fixture(t,{source:'claude-code',relative:'.claude/settings.json',format:'json',content:'{"note":"{{SECRET:note}}","theme":"dark"}',before:'{"foreign":true}',mode:'merge',values:{'SECRET:note':local}});
  const plan=await f.plan();assert.equal(plan.ready,true);assert.equal(JSON.stringify(plan).includes(local),false);
  const receipt=await f.core.prepare(plan.handle,plan.plan_hash);assert.equal(receipt.ok,true);assert.equal(JSON.stringify(f.state.dialogs).includes(local),false);
  assert.equal(JSON.parse(f.state.dialogs[0].previews[0].after.content).note,'{{SECRET:note}}');
  for(const entry of f.disk()){assert.equal(entry.bytes.includes(Buffer.from(local)),false);assert.equal(entry.bytes.includes(Buffer.from(JSON.stringify(local))),false);}
  const data=f.store.read(receipt.transaction_id,profile(f.home,process.platform,f.state.osUser).id);assert.equal(JSON.parse(data.targets[0].after.bytes).note,local);data.close();
});
test('text local values and HOME are masked while exact generated bytes remain only in sealed snapshots',async t=>{
  const local='LocalNickname';const f=fixture(t,{lowEntropyPath:true,content:'Use {{NAME}} at {{HOME}}.\n',values:{NAME:local}}),receipt=await f.prepare();
  assert.equal(receipt.ok,true);const serialized=JSON.stringify(f.state.dialogs);assert.equal(serialized.includes(local),false);assert.equal(serialized.includes(f.home),false);assert.match(serialized,/NAME/);
});
test('a synthetic high-entropy HOME is withheld rather than weakening the preview privacy guard',()=>{
  const {maskedPreview}=require('../src/borrow/transaction-plan');
  const home='/private/var/folders/xy/j4fl9vqj2sv4fd_3m9hj6p9c0000gn/T/plexiform-setups-transaction-ABC123/profile';
  const preview=maskedPreview(Buffer.from('Use LocalNickname at '+home+'.\n'),
    {relative:'.codex/AGENTS.md',format:'text'},new Map([['NAME','LocalNickname'],['HOME',home]]),{profile:{root:home}});
  assert.deepEqual(preview,{status:'withheld',content:null});
});
test('plans require explicit instruction/code choices and deny unregistered selection or fields',async t=>{
  const f=fixture(t);for(const patch of [{instructions:false},{code:false},{mode:'merge'},{replace_keys:['foreign']},{path:'/tmp/evil'}]){
    const request=f.request();Object.assign(request.files[0],patch);assert.equal((await f.core.plan(f.sourceHandle,request)).ok,false);
  }
  const request=f.request();request.files[0].id=crypto.randomUUID();assert.equal((await f.core.plan(f.sourceHandle,request)).ok,false);assert.equal(f.disk().length,0);
});
test('TOML mapping is an honest unavailable adapter with no prepare grant',async t=>{
  const f=fixture(t,{relative:'.codex/config.toml',format:'toml',content:'model = "example"\n',before:'model = "local"\n'}),plan=await f.plan();
  assert.equal(plan.ok,true);assert.equal(plan.ready,false);assert.equal(plan.targets[0].status,'adapter_unavailable');assert.equal((await f.core.prepare(plan.handle,plan.plan_hash)).ok,false);assert.equal(f.disk().length,0);
});
test('duplicate-key current JSON is refused rather than silently discarding local values',async t=>{
  const f=fixture(t,{source:'claude-code',relative:'.claude/settings.json',format:'json',content:'{"theme":"dark"}',before:'{"theme":"light","th\\u0065me":"custom"}',mode:'merge'});
  assert.equal((await f.plan()).ok,false);assert.equal(fs.readFileSync(f.filename,'utf8'),'{"theme":"light","th\\u0065me":"custom"}');assert.equal(f.disk().length,0);
});
test('source principal mismatch and source-read exceptions are closed without secret error text',async t=>{
  const f=fixture(t);f.source.principal={...f.source.principal,member:'other'};assert.equal((await f.plan()).ok,false);
  f.state.readHook=()=>{throw new Error('private provider secret must not escape');};const result=await f.plan();assert.equal(result.ok,false);assert.equal(JSON.stringify(result).includes('private provider'),false);
});
for(const field of ['account','team','member','device'])test(`held source read refuses a changed captured ${field}`,async t=>{
  const f=fixture(t),held=deferred();f.state.readHook=()=>held.promise;const result=f.plan();f.state.actor={...f.state.actor,[field]:'other'};held.resolve(f.source);
  assert.equal((await result).ok,false);assert.equal(f.state.dialogs.length,0);assert.equal(f.disk().length,0);
});
test('source await rechecks expiry and current foreground generation',async t=>{
  for(const change of [f=>{f.state.time+=CORE_LIMITS.ttlMs;},f=>{f.state.foreground=false;},f=>{f.state.generation++;}]) {
    const f=fixture(t),held=deferred();f.state.readHook=()=>held.promise;const pending=f.plan();change(f);held.resolve(f.source);assert.equal((await pending).ok,false);
  }
});
test('plan snapshots the request before a held source read so edited dialog values cannot retarget it',async t=>{
  const f=fixture(t,{content:'Name {{NAME}}.\n',values:{NAME:'FirstName'}}),held=deferred(),request=f.request();
  f.state.readHook=()=>held.promise;const pending=f.core.plan(f.sourceHandle,request);request.values.NAME='LaterName';request.files[0].instructions=false;held.resolve(f.source);
  const plan=await pending;assert.equal(plan.ready,true);f.state.readHook=null;const receipt=await f.core.prepare(plan.handle,plan.plan_hash);assert.equal(receipt.ok,true);
  const data=f.store.read(receipt.transaction_id,profile(f.home,process.platform,f.state.osUser).id);assert.equal(data.targets[0].after.bytes.toString(),'Name FirstName.\n');data.close();
});
test('prepare is one-use across concurrent retry calls',async t=>{
  const f=fixture(t),plan=await f.plan(),held=deferred();f.state.confirmHook=()=>held.promise;
  const first=f.core.prepare(plan.handle,plan.plan_hash),second=await f.core.prepare(plan.handle,plan.plan_hash);assert.equal(second.ok,false);await yieldTurn();assert.equal(f.state.dialogs.length,1);
  held.resolve({approved:true,plan_hash:plan.plan_hash});assert.equal((await first).ok,true);assert.equal(f.core.listRecovery().transactions.length,1);assert.equal((await f.core.prepare(plan.handle,plan.plan_hash)).ok,false);
});
test('fresh immutable source version and current credential owner are required again at prepare',async t=>{
  const f=fixture(t),plan=await f.plan();f.source.versionId=crypto.randomUUID();assert.equal((await f.core.prepare(plan.handle,plan.plan_hash)).ok,false);assert.equal(f.state.dialogs.length,0);assert.equal(f.disk().length,0);
});
test('held native confirmation rechecks TTL, account, device, source availability and local generation',async t=>{
  for(const change of [f=>{f.state.time+=CORE_LIMITS.ttlMs;},f=>{f.state.actor={...f.state.actor,account:'other'};},f=>{f.state.actor={...f.state.actor,device:'other'};},f=>{f.state.sourceCurrent=false;},f=>{f.core.invalidate();}]) {
    const f=fixture(t),plan=await f.plan(),held=deferred();f.state.confirmHook=()=>held.promise;const pending=f.core.prepare(plan.handle,plan.plan_hash);await yieldTurn();change(f);held.resolve({approved:true,plan_hash:plan.plan_hash});assert.equal((await pending).ok,false);assert.equal(f.disk().length,0);
  }
});
test('canonical profile alias retarget during a native dialog refuses',async t=>{
  const f=fixture(t),alias=path.join(f.temp,'alias');fs.symlinkSync(f.home,alias);f.state.profilePath=alias;
  const plan=await f.plan(),held=deferred();f.state.confirmHook=()=>held.promise;const pending=f.core.prepare(plan.handle,plan.plan_hash);await yieldTurn();
  const other=path.join(f.temp,'other-profile');fs.mkdirSync(other,{mode:0o700});fs.unlinkSync(alias);fs.symlinkSync(other,alias);held.resolve({approved:true,plan_hash:plan.plan_hash});assert.equal((await pending).ok,false);assert.equal(f.disk().length,0);
});
test('held canonical-profile queue validates owner inside the queue before a second read or dialog',async t=>{
  const f=fixture(t),first=await f.plan(),second=await f.plan(),held=deferred();f.state.confirmHook=()=>held.promise;
  const a=f.core.prepare(first.handle,first.plan_hash);await yieldTurn();const b=f.core.prepare(second.handle,second.plan_hash);await yieldTurn();assert.equal(f.state.calls,3);assert.equal(f.state.dialogs.length,1);
  f.state.actor={...f.state.actor,account:'other'};held.resolve({approved:true,plan_hash:first.plan_hash});assert.equal((await a).ok,false);assert.equal((await b).ok,false);assert.equal(f.state.calls,3);assert.equal(f.state.dialogs.length,1);assert.equal(f.disk().length,0);
});
test('local human edits, same-byte inode replacement and mode changes after review all refuse without loss',async t=>{
  for(const change of [f=>fs.writeFileSync(f.filename,'New human edit.\n'),f=>{fs.renameSync(f.filename,f.filename+'.preserved');fs.writeFileSync(f.filename,'Keep existing notes.\n',{mode:0o600});},f=>fs.chmodSync(f.filename,0o640)]) {
    const f=fixture(t),plan=await f.plan(),held=deferred();f.state.confirmHook=()=>held.promise;const pending=f.core.prepare(plan.handle,plan.plan_hash);await yieldTurn();change(f);const changed=fs.readFileSync(f.filename);held.resolve({approved:true,plan_hash:plan.plan_hash});assert.equal((await pending).ok,false);assert.deepEqual(fs.readFileSync(f.filename),changed);assert.equal(f.disk().length,0);
  }
});
test('snapshot fsync precedes manifest declaration and transaction parent durability',async t=>{
  const events=[],descriptors=new Map();const api=new Proxy(fs,{get(target,key){if(key==='openSync')return (...args)=>{const fd=target.openSync(...args);descriptors.set(fd,String(args[0]));return fd;};if(key==='fsyncSync')return fd=>{events.push(descriptors.get(fd));return target.fsyncSync(fd);};return target[key];}});
  const f=fixture(t,{store:{fsApi:api}}),receipt=await f.prepare();assert.equal(receipt.ok,true);
  const manifest=events.findIndex(name=>name.endsWith('manifest.sealed'));for(const role of ['before','base','after'])assert.ok(events.findIndex(name=>name.endsWith(`0-${role}.sealed`))<manifest);
  assert.equal(events.at(-1),fs.realpathSync(f.root));
});
test('crash before prepared manifest leaves only encrypted incomplete recovery and never prunes it',async t=>{
  const descriptors=new Map();const api=new Proxy(fs,{get(target,key){if(key==='openSync')return (...args)=>{const fd=target.openSync(...args);descriptors.set(fd,String(args[0]));return fd;};if(key==='writeSync')return (fd,...args)=>{if(descriptors.get(fd)?.endsWith('manifest.sealed'))throw new Error('simulated crash');return target.writeSync(fd,...args);};return target[key];}});
  const f=fixture(t,{store:{fsApi:api}});assert.equal((await f.prepare()).ok,false);
  const recovery=f.makeCore({store:f.makeStore()}).listRecovery();assert.equal(recovery.ok,true);assert.equal(recovery.transactions.length,1);assert.equal(recovery.transactions[0].status,'incomplete');
  for(const entry of f.disk())assert.equal(entry.bytes.includes(Buffer.from('Keep existing notes.')),false);
  assert.equal(fs.readFileSync(f.filename,'utf8'),'Keep existing notes.\n');
});
test('incomplete transaction bound refuses rather than deleting recoverable records',async t=>{
  const f=fixture(t);f.store.list();for(let i=0;i<STORE_LIMITS.incomplete;i++)fs.mkdirSync(path.join(f.root,'.pending.'+crypto.randomUUID()),{mode:0o700});
  const before=fs.readdirSync(f.root).sort();assert.equal((await f.prepare()).ok,false);assert.deepEqual(fs.readdirSync(f.root).sort(),before);
});
test('missing OS key wrapping refuses without plaintext storage fallback',async t=>{
  const f=fixture(t,{store:{wrapping:{available:()=>false,wrap(){throw Error('must not call');},unwrap(){throw Error('must not call');}}}});
  assert.equal((await f.prepare()).ok,false);assert.equal(fs.existsSync(f.root),false);
});
test('an obvious plaintext key wrapper is refused before any secret snapshot is written',async t=>{
  const f=fixture(t,{store:{wrapping:{available:()=>true,wrap:key=>Buffer.from(key),unwrap:bytes=>Buffer.from(bytes)}}});
  assert.equal((await f.prepare()).ok,false);assert.deepEqual(fs.readdirSync(f.root),[]);assert.equal(fs.readFileSync(f.filename,'utf8'),'Keep existing notes.\n');
});
test('read-only plan concurrency is bounded before starting a fifth source request',async t=>{
  const f=fixture(t),held=deferred();f.state.readHook=()=>held.promise;
  const pending=Array.from({length:CORE_LIMITS.concurrency},()=>f.plan());assert.equal((await f.plan()).ok,false);assert.equal(f.state.calls,CORE_LIMITS.concurrency);
  held.resolve(f.source);for(const result of await Promise.all(pending))assert.equal(result.ok,true);
});
test('safeStorage wrapper refuses Linux basic_text, unknown, absent backend and availability changes',()=>{
  let available=true,backend='basic_text',encryptCalls=0;
  const safe={isEncryptionAvailable:()=>available,getSelectedStorageBackend:()=>backend,encryptString(value){encryptCalls++;return Buffer.from('sealed:'+value);},decryptString:value=>value.toString().slice(7)};
  const wrapper=safeStorageWrapping(safe,'linux');for(const name of ['basic_text','unknown','future-unreviewed']){backend=name;assert.equal(wrapper.available(),false);assert.throws(()=>wrapper.wrap(Buffer.alloc(32)));}
  backend='kwallet6';assert.equal(wrapper.available(),true);assert.equal(wrapper.unwrap(wrapper.wrap(Buffer.alloc(32,7))).equals(Buffer.alloc(32,7)),true);
  available=false;assert.throws(()=>wrapper.unwrap(Buffer.alloc(60)));assert.equal(encryptCalls,1);delete safe.getSelectedStorageBackend;available=true;assert.equal(wrapper.available(),false);
});
test('manifest/snapshot ciphertext tampering, role swapping and wrong profile cannot decrypt',async t=>{
  for(const kind of ['manifest','snapshot','roles','profile']) {
    const f=fixture(t),receipt=await f.prepare();assert.equal(receipt.ok,true);const directory=path.join(f.root,receipt.transaction_id),profileId=profile(f.home,process.platform,f.state.osUser).id;
    if(kind==='manifest'||kind==='snapshot'){const name=kind==='manifest'?'manifest.sealed':'0-before.sealed',file=path.join(directory,name),value=JSON.parse(fs.readFileSync(file)),data=Buffer.from(value.envelope.data,'base64');data[0]^=1;value.envelope.data=data.toString('base64');fs.writeFileSync(file,JSON.stringify(value));}
    if(kind==='roles'){const a=path.join(directory,'0-before.sealed'),b=path.join(directory,'0-after.sealed'),bytes=fs.readFileSync(a);fs.writeFileSync(a,fs.readFileSync(b));fs.writeFileSync(b,bytes);}
    assert.throws(()=>f.store.read(receipt.transaction_id,kind==='profile'?'0'.repeat(64):profileId));assert.equal(fs.readFileSync(f.filename,'utf8'),'Keep existing notes.\n');
  }
});
test('journal directories reject foreign names, links, hardlinks and broad permissions without removing bytes',async t=>{
  for(const kind of ['foreign','symlink','hardlink','permissions']) {
    const f=fixture(t),receipt=await f.prepare();assert.equal(receipt.ok,true);const directory=path.join(f.root,receipt.transaction_id),file=path.join(directory,'0-before.sealed'),original=fs.readFileSync(file);
    if(kind==='foreign')fs.writeFileSync(path.join(directory,'arbitrary-owned-config'),original,{mode:0o600});
    if(kind==='symlink'){fs.renameSync(file,file+'.preserved');fs.symlinkSync(f.filename,file);}
    if(kind==='hardlink')fs.linkSync(file,path.join(f.temp,'preserved'));
    if(kind==='permissions')fs.chmodSync(file,0o644);
    assert.equal(f.core.listRecovery().ok,false);assert.equal(fs.readFileSync(f.filename,'utf8'),'Keep existing notes.\n');
  }
});
test('restart recovery is locked and requires a separate confirmation before any old preview',async t=>{
  const f=fixture(t),receipt=await f.prepare();assert.equal(receipt.ok,true);f.state.actor=null;f.state.sourceCurrent=false;f.state.generation++;
  const core=f.makeCore({store:f.makeStore()}),listed=core.listRecovery();assert.equal(listed.ok,true);assert.equal(listed.status,'locked');assert.equal(JSON.stringify(listed).includes('codex'),false);assert.equal(JSON.stringify(listed).includes('team-a'),false);
  const calls=f.state.calls;f.state.confirmHook=request=>{assert.deepEqual(Object.keys(request).sort(),['kind','meaning','transaction_id']);return {approved:false,transaction_id:request.transaction_id};};
  assert.equal((await core.recover(receipt.transaction_id)).ok,false);assert.equal(f.state.calls,calls);assert.equal(fs.readFileSync(f.filename,'utf8'),'Keep existing notes.\n');
});
test('fresh offline own-local recovery reads snapshots without restoring remote authority or exposing filled values',async t=>{
  const local='LocalOnlyValue';const f=fixture(t,{content:'Write {{NAME}}.\n',values:{NAME:local}}),receipt=await f.prepare();assert.equal(receipt.ok,true);
  f.state.actor=null;f.state.sourceCurrent=false;f.state.generation++;const core=f.makeCore({store:f.makeStore()}),calls=f.state.calls,recovered=await core.recover(receipt.transaction_id);
  assert.equal(recovered.ok,true);assert.equal(recovered.recovery_authority,'own_local_review_only');assert.equal(recovered.targets[0].status,'content_matches_before');assert.equal(recovered.target_files_changed,false);assert.equal(f.state.calls,calls);
  const preview=core.reviewRecovery(recovered.handle);assert.equal(preview.ok,true);assert.equal(preview.previews[0].after.content,null);assert.equal(JSON.stringify(preview).includes(local),false);assert.match(preview.previews[0].shared.content,/\{\{NAME\}\}/);
});
test('old recovery dialog and preview handles are invalidated by foreground/account/device/generation changes',async t=>{
  for(const change of [f=>{f.state.foreground=false;},f=>{f.state.actor={...f.state.actor,account:'other'};},f=>{f.state.actor={...f.state.actor,device:'other'};},f=>{f.state.generation++;}]) {
    const f=fixture(t),receipt=await f.prepare(),core=f.makeCore(),held=deferred();f.state.confirmHook=()=>held.promise;
    const pending=core.recover(receipt.transaction_id);await yieldTurn();change(f);held.resolve({approved:true,transaction_id:receipt.transaction_id});assert.equal((await pending).ok,false);
  }
  const f=fixture(t),receipt=await f.prepare(),recovered=await f.core.recover(receipt.transaction_id);assert.equal(recovered.ok,true);f.state.generation++;assert.equal(f.core.reviewRecovery(recovered.handle).ok,false);
});
test('foreign edits after restart are reported as changed and preserved without automatic restoration',async t=>{
  const f=fixture(t),receipt=await f.prepare();assert.equal(receipt.ok,true);fs.writeFileSync(f.filename,'Human work after preparation.\n');
  const recovered=await f.makeCore({store:f.makeStore()}).recover(receipt.transaction_id);assert.equal(recovered.ok,true);assert.equal(recovered.targets[0].status,'changed');assert.equal(fs.readFileSync(f.filename,'utf8'),'Human work after preparation.\n');
});
test('a different canonical OS profile cannot unlock or preview an old transaction',async t=>{
  const f=fixture(t),receipt=await f.prepare();assert.equal(receipt.ok,true);const other=path.join(f.temp,'other');fs.mkdirSync(other,{mode:0o700});f.state.profilePath=other;
  const dialogs=f.state.dialogs.length;assert.equal((await f.core.recover(receipt.transaction_id)).ok,false);assert.equal(f.state.dialogs.length,dialogs);
});
test('recovery awaits recheck expiry and require an exact fresh transaction confirmation',async t=>{
  const f=fixture(t),receipt=await f.prepare(),held=deferred();f.state.confirmHook=()=>held.promise;const pending=f.core.recover(receipt.transaction_id);await yieldTurn();
  f.state.time+=CORE_LIMITS.ttlMs;held.resolve({approved:true,transaction_id:receipt.transaction_id});assert.equal((await pending).ok,false);
  f.state.confirmHook=()=>({approved:true,transaction_id:crypto.randomUUID()});assert.equal((await f.core.recover(receipt.transaction_id)).ok,false);
});
