'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{EventEmitter}=require('node:events');
const source=fs.readFileSync(path.join(__dirname,'..','main.js'),'utf8');
const cut=(start,end)=>source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));
const create=cut('function createWindow() {','\nfunction createSettingsWindow()');const guard=cut('function guardRenderer(w, name, recreate) {','\n// Quitting must');const broadcast=cut('function broadcastStatus() {','\n// ── Roaming:');
function fixture(){
const windows=[],pending=[],effects=[];
class Window extends EventEmitter{constructor(){super();this.dead=false;this.visible=false;this.minimized=false;this.crashed=false;this.webContents=new EventEmitter();this.webContents.isCrashed=()=>this.crashed;this.webContents.reloadIgnoringCache=()=>{throw Error('dead renderer');};this.webContents.send=()=>{if(this.dead)throw Error('disposed send');effects.push('send');};windows.push(this);}isDestroyed(){return this.dead;}isVisible(){if(this.dead)throw Error('disposed visibility');return this.visible;}isMinimized(){if(this.dead)throw Error('disposed minimized');return this.minimized;}showInactive(){this.visible=true;}setAlwaysOnTop(){}setVisibleOnAllWorkspaces(){}setAspectRatio(){}loadFile(){}destroy(){if(this.fail)throw Error('disposal refused');this.dead=true;this.emit('closed');}}
const c={BrowserWindow:Window,readBounds:()=>null,screen:{getPrimaryDisplay:()=>({workAreaSize:{width:1000,height:800}})},WIDGET_ASPECT:64/82,MIN_WIDTH:32,MAX_WIDTH:300,path,__dirname:'/synthetic',loadConfig:()=>({showWidget:true}),setTimeout:()=>1,queueMicrotask:f=>pending.push(f),saveBounds:()=>effects.push('save'),glideTimer:null,console:{log(){}},win:null,widgetAsksSent:null,lightsWin:null,onboardingWin:null,buddyWin:null,helpWin:null,waitingWin:null,travelLook:null,gardenRun:null,roamState:{busy:false},stateMemo:{},aggregateState:()=>({sessions:[],look:{}}),askKey:()=>'',statusPushWanted:()=>false,DEMO:true,devMockReady:false,localSessions:()=>[],BusyWatch:{observe:()=>null},maybeNotify(){},updateOverlay(){},WorkScopeView:{trayItem:()=>null},WorkScope:{},trayScopeKey:'null',stripAway:false,stripBudget:false,budgetNotices:{list:()=>[]},updateRowShown:false,applyStrip(){},updateGarden(){},maybeRoam(){},maybeRandomEvent(){}};
vm.createContext(c);vm.runInContext(create+'\n'+guard+'\n'+broadcast,c);
const Gate=require('../src/motion-gate').createMotionGate;c.widgetMotion=Gate(paused=>{if(c.win&&!c.win.isDestroyed())c.win.webContents.send('motion-paused',paused);if(!paused)c.broadcastStatus();});c.setMotionPaused=(r,v)=>c.widgetMotion.set(r,!!v);
return{c,windows,effects,make:()=>c.createWindow(),flush(){while(pending.length)pending.shift()();},live:()=>windows.filter(w=>!w.dead).length};}
test('full actual watchdog retains current owner when destruction refuses',()=>{const f=fixture(),old=f.make();old.crashed=true;old.fail=true;f.c.broadcastStatus();f.flush();assert.equal(f.c.win,old);assert.equal(f.live(),1);});
test('actual motion unpause watchdog replacement stops obsolete visibility handler',()=>{const f=fixture(),old=f.make();old.minimized=true;f.c.setMotionPaused('minimized',true);old.minimized=false;old.visible=true;old.crashed=true;assert.doesNotThrow(()=>old.emit('restore'));f.flush();assert.equal(f.live(),1);assert.notEqual(f.c.win,old);});
test('actual watchdog and deferred failed-reload recovery converge after successful disposal',()=>{const f=fixture(),old=f.make();old.crashed=true;old.webContents.emit('render-process-gone',{}, {reason:'crashed'});f.c.broadcastStatus();f.flush();assert.equal(f.live(),1);assert.notEqual(f.c.win,old);assert.equal(f.windows.length,2);});
test('replacement cannot be altered by every obsolete event after actual successful watchdog disposal',()=>{const f=fixture(),old=f.make();old.crashed=true;f.c.broadcastStatus();f.flush();const next=f.c.win;f.effects.length=0;for(const e of ['closed','show','hide','resize','move','restore','minimize'])old.emit(e);old.webContents.emit('did-finish-load');old.webContents.emit('render-process-gone',{}, {reason:'crashed'});f.flush();assert.equal(f.c.win,next);assert.equal(f.live(),1);assert.deepEqual(f.effects,[]);});
test('actual hidden restore unpause rechecks owner before second motion read',()=>{const f=fixture(),old=f.make();old.minimized=true;f.c.setMotionPaused('minimized',true);old.minimized=false;old.visible=false;old.crashed=true;assert.doesNotThrow(()=>old.emit('restore'));f.flush();assert.equal(f.live(),1);assert.notEqual(f.c.win,old);});

test('actual finished-load second synchronization cannot send after hidden unpause replaces owner',()=>{const f=fixture(),old=f.make();f.c.setMotionPaused('hidden',true);old.visible=true;old.crashed=true;let loads=0;const prior=f.c.broadcastStatus;f.c.broadcastStatus=()=>{if(++loads>1)prior();};assert.doesNotThrow(()=>old.webContents.emit('did-finish-load'));f.flush();assert.equal(f.live(),1);assert.notEqual(f.c.win,old);});
