const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('lightsApi', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveConfig: (partial) => ipcRenderer.invoke('save-config', partial),
  resetRules: () => ipcRenderer.invoke('reset-rules'),
  getAggregateStatus: () => ipcRenderer.invoke('get-aggregate-status'),
  getStats: (days) => ipcRenderer.invoke('get-stats', days),
  exportStats: (format, days) => ipcRenderer.invoke('export-stats', format, days),
  getCosts: () => ipcRenderer.invoke('get-costs'),
  getUsageSummary: (opts) => ipcRenderer.invoke('get-usage-summary', opts),
  routerOverview: () => ipcRenderer.invoke('router-overview'),
  routerSetEnabled: (on) => ipcRenderer.invoke('router-set-enabled', on),
  routerSwitch: (on) => ipcRenderer.invoke('router-switch', on),
  routerSwitchSession: (sessionId) => ipcRenderer.invoke('router-switch-session', sessionId),
  getSavings: () => ipcRenderer.invoke('get-savings'),
  routerRevealShim: () => ipcRenderer.invoke('router-reveal-shim'),
  delegationSetEnabled: (on) => ipcRenderer.invoke('delegation-set-enabled', on),
  delegationOverview: () => ipcRenderer.invoke('delegation-overview'),
  delegationDiet: (opts) => ipcRenderer.invoke('delegation-diet', opts),
  previewSound: (name) => ipcRenderer.invoke('preview-sound', name),
  chooseSoundFile: () => ipcRenderer.invoke('choose-sound-file'),
  exportRules: (rules) => ipcRenderer.invoke('export-rules', rules),
  importRules: () => ipcRenderer.invoke('import-rules'),
  connectAgent: (which) => ipcRenderer.invoke('connect-agent', which),
  signalEndpoint: () => ipcRenderer.invoke('signal-endpoint'),
  previewOnWidget: (look, ms) => ipcRenderer.invoke('preview-on-widget', look, ms),
  openPreferences: () => ipcRenderer.invoke('open-preferences'),
  cameos: {
    list: () => ipcRenderer.invoke('cameos-list'),
    chooseFile: () => ipcRenderer.invoke('cameos-choose-file'),
    add: (payload) => ipcRenderer.invoke('cameos-add', payload),
    remove: (id) => ipcRenderer.invoke('cameos-remove', id),
  },
  onStatusChanged: (callback) => ipcRenderer.on('status-changed', callback),
  onShowView: (cb) => ipcRenderer.on('show-view', (e, v) => cb(v)),
});
