const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('trafficLight', {
  openClaude: () => ipcRenderer.invoke('open-claude'),
  goToNeedingSession: () => ipcRenderer.invoke('go-to-needing-session'),
  getAggregateStatus: () => ipcRenderer.invoke('get-aggregate-status'),
  cursorInWindow: () => ipcRenderer.invoke('cursor-in-window'),
  getWindowPosition: () => ipcRenderer.invoke('get-window-position'),
  setWindowPosition: (x, y) => ipcRenderer.send('set-window-position', x, y),
  dragStart: () => ipcRenderer.send('drag-start'),
  dragEnd: (vx, vy) => ipcRenderer.send('drag-end', vx, vy),
  onLand: (cb) => ipcRenderer.on('land', (e, strength) => cb(strength)),
  onImpact: (cb) => ipcRenderer.on('impact', (e, side, strength) => cb(side, strength)),
  onSway: (cb) => ipcRenderer.on('sway', (e, degPerSec) => cb(degPerSec)),
  onLean: (cb) => ipcRenderer.on('lean', (e, vx) => cb(vx)),
  onEyes: (cb) => ipcRenderer.on('eyes', (e, x, y) => cb(x, y)),
  onVisibility: (cb) => ipcRenderer.on('visibility', (e, visible) => cb(visible)),
  setReducedMotion: (on) => ipcRenderer.send('reduced-motion', on),
  setClickThrough: (ignore) => ipcRenderer.send('set-click-through', ignore),
  resizeWindowBy: (factor) => ipcRenderer.send('resize-window-by', factor),
  onStatusChanged: (callback) => ipcRenderer.on('status-changed', callback),
  openLights: () => ipcRenderer.invoke('open-lights'),
  openHelp: () => ipcRenderer.invoke('open-help'),
  onBurst: (cb) => ipcRenderer.on('burst', (e, ms) => cb(ms)),
  onAim: (cb) => ipcRenderer.on('aim', (e, a) => cb(a)),
  onEvent: (cb) => ipcRenderer.on('event', (e, name) => cb(name)),
  onSoundFlash: (cb) => ipcRenderer.on('sound-flash', () => cb()),
  answerRequest: (id, decision) => ipcRenderer.invoke('answer-request', id, decision),
  gesture: (g) => ipcRenderer.invoke('gesture', g),
  awayOpen: (i) => ipcRenderer.invoke('away-open', i),
  awayDismiss: () => ipcRenderer.invoke('away-dismiss'),
  // Push-to-talk (F7): long-press starts and ends a question; main pushes
  // listening / thinking / talking / idle / error back for the mic badge and the mouth.
  voiceEnabled: () => ipcRenderer.invoke('voice-enabled'),
  voiceStart: () => ipcRenderer.invoke('voice-start'),
  voiceStop: () => ipcRenderer.invoke('voice-stop'),
  onVoice: (cb) => ipcRenderer.on('voice-state', (e, st) => cb(st)),
});
