'use strict';
const api=window.setupsApi,teams=document.getElementById('teams'),review=document.getElementById('review'),status=document.getElementById('status');
let sources=[],draft=null,chosen=null;
const el=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);return node;};
const button=(text,fn)=>{const node=el('button',text);node.type='button';node.onclick=async()=>{node.disabled=true;try{await fn();}catch{status.textContent='This operation is unavailable. Refresh current team access.';}finally{node.disabled=false;}};return node;};
const tell=result=>{status.textContent=result?.ok?'Saved.':result?.error??'This operation is unavailable. Refresh current team access.';return result?.ok;};
async function refresh(){draft=null;chosen=null;review.replaceChildren();teams.replaceChildren();const state=await api.state();sources=state?.sources??[];status.textContent=state?.status==='complete'?'Current team access loaded.':state?.teams?.length?'Some team setups are unavailable.':state?.status==='partial'||state?.status==='unavailable'?'Current team access is unavailable. Refresh after signing in or reconnecting.':'Sign in and join a team to share or review setups.';
  for(const team of state?.teams??[]){const section=el('section');section.append(el('h2',team.name),el('p',team.status==='complete'?`${team.role} · ${team.profiles.length} shared setups`:'Setups unavailable or incomplete. Refresh to retry.'));
    if(team.baseline)section.append(el('p',team.baseline.required?'Team baseline is a required reminder. It does not enforce installation.':'Team baseline is an optional reminder.'));
    for(const profile of team.profiles??[]){const row=el('div');row.className='row';row.append(el('span',`${profile.own?'Your setup':'Team setup'} · version ${profile.version} · ${profile.files} files · ${profile.items} inventory entries`),button('Review',()=>openProfile(profile,team)));section.append(row);}
    if(team.handle&&team.role!=='viewer'&&team.status!=='unavailable')section.append(button('Select files to share',()=>chooseSources(team)));
    teams.append(section);
  }
}
function chooseSources(team){draft=null;chosen=null;review.replaceChildren(el('h2',`Share with ${team.name}`),el('p','Choose allowlisted tools to inspect on this Mac. Raw files stay local. Only scrubbed text reaches this review. No listing commands will run.'));
  const checks=[],list=el('div');list.className='sources';for(const source of sources){const label=el('label'),check=el('input');check.type='checkbox';check.value=source.id;label.append(check,document.createTextNode(` ${source.label}${source.optIn?' (sensitive; opt in)':''}`));list.append(label);checks.push(check);}review.append(list);
  const label=el('label'),inventory=el('input');inventory.type='checkbox';label.append(inventory,document.createTextNode(' Include saved plugin and extension inventory files. No package listing commands.'));review.append(label);
  review.append(button('Inspect selected files',async()=>{const picked=checks.filter(c=>c.checked).map(c=>c.value),result=await api.draft(team.handle,{sources:picked,inventory:inventory.checked,ssh:picked.includes('ssh-config')});if(tell(result)){draft=result;renderDraft();}}));review.scrollIntoView({block:'start'});
}
function renderDraft(){const active=document.activeElement;review.replaceChildren(el('h2','Review every complete file'),el('p','Review filenames and remove private details from the full text and notes. Every edit clears file approvals. Unknown private prose needs your review; automated scrubbing cannot identify everything.'));
  if(draft.error)review.append(el('p',draft.error));if(draft.scan_summary?.limited||draft.scan_summary?.skipped)review.append(el('p',`Inspection skipped ${draft.scan_summary.skipped} entries${draft.scan_summary.limited?' after reaching a scan limit':''}. Only displayed entries can be shared.`));
  for(const file of draft.payload.files){const section=el('section');section.append(el('h3',`${file.source_id} · ${file.relative_path}`));const text=el('textarea');text.className='file-text';text.value=file.content;text.setAttribute('aria-label',`Complete ${file.relative_path} text`);text.oninput=()=>{draft.content_hash=null;review.querySelectorAll('input[type=checkbox],button').forEach(node=>{if(node.textContent==='Share reviewed setup'||node.type==='checkbox')node.disabled=true;});};const note=el('textarea');note.value=file.note;note.setAttribute('aria-label',`${file.relative_path} note`);note.oninput=text.oninput;const save=async()=>{const result=await api.edit(draft.handle,{file_id:file.id,content:text.value,note:note.value});if(result?.ok){draft=result;renderDraft();}else tell(result);};section.append(text,note,button('Save reviewed edits',save),button('Exclude this file',async()=>{const result=await api.edit(draft.handle,{file_id:file.id,remove:true});if(result?.ok){draft=result;renderDraft();}else tell(result);}));const label=el('label'),check=el('input');check.type='checkbox';check.checked=draft.approved_files.includes(file.id);check.disabled=check.checked||!draft.content_hash;check.onchange=async()=>{if(!draft.content_hash)return;const hash=draft.file_hashes.find(h=>h.file_id===file.id)?.hash,result=await api.approve(draft.handle,file.id,hash);if(result?.ok){draft=result;renderDraft();}else tell(result);};label.append(check,document.createTextNode(' I reviewed the full saved text and note for secrets and private details.'));section.append(label);review.append(section);}
  const inventory=el('pre',draft.payload.items.map(i=>`${i.kind}: ${i.name}${i.version?` (${i.version})`:''}`).join('\n')||'No inventory entries selected.');review.append(el('h3','Inventory'),inventory);for(const item of draft.payload.items)review.append(button(`Exclude ${item.name}`,async()=>{const result=await api.edit(draft.handle,{item_id:item.id,remove:true});if(result?.ok){draft=result;renderDraft();}else tell(result);}));
  const note=el('textarea');note.value=draft.payload.note;note.setAttribute('aria-label','Profile note');note.oninput=()=>{draft.content_hash=null;review.querySelectorAll('input[type=checkbox],button').forEach(node=>{if(node.textContent==='Share reviewed setup'||node.type==='checkbox')node.disabled=true;});};review.append(el('h3','Profile note'),note,button('Save profile note',async()=>{const result=await api.edit(draft.handle,{profile_note:note.value});if(result?.ok){draft=result;renderDraft();}else tell(result);}));
  const label=el('label'),check=el('input');check.type='checkbox';label.append(check,document.createTextNode(' I reviewed all saved inventory, notes and full file text, and want to share this exact setup with the selected team.'));const share=button('Share reviewed setup',async()=>{if(tell(await api.publish(draft.handle,draft.content_hash)))await refresh();});share.disabled=true;check.onchange=()=>{share.disabled=!check.checked||!draft.content_hash||draft.approved_files.length!==draft.payload.files.length;};review.append(label,share);
}
async function openProfile(profile,team){draft=null;const data=await api.read(profile.handle);if(!tell(data))return;chosen={profile,team,data};review.replaceChildren(el('h2',`Setup version ${data.version}`));const versionRow=el('div');versionRow.className='row';for(const version of data.versions??[])versionRow.append(button(`Review version ${version.number}`,()=>openProfile({...profile,handle:version.handle},team)));review.append(versionRow);const ids=[];for(const file of data.payload.files){const section=el('section'),label=el('label'),check=el('input');check.type='checkbox';check.value=file.id;ids.push(check);label.append(check,document.createTextNode(` ${file.relative_path}`));section.append(label,el('pre',file.content),el('p',file.note));review.append(section);}for(const item of data.payload.items){const label=el('label'),check=el('input');check.type='checkbox';check.value=item.id;ids.push(check);label.append(check,document.createTextNode(` ${item.kind}: ${item.name} ${item.version??''}`));review.append(label);}review.append(el('p',data.payload.note));
  const selected=()=>ids.filter(c=>c.checked).map(c=>c.value);
  review.append(button('Record selected entries as reviewed',async()=>tell(await api.action(profile.handle,'receipt',{selection:selected(),outcome:'reviewed'}))));
  if(['owner','admin'].includes(team.role)){const label=el('label'),required=el('input');required.type='checkbox';label.append(required,document.createTextNode(' Required reminder for the team'));review.append(label,button('Set selected team baseline',async()=>{if(tell(await api.action(profile.handle,'baseline',{selection:selected(),required:required.checked})))await refresh();}));}
  if(data.own)review.append(button('Export your shared setup',async()=>tell(await api.export(profile.handle))));
  if(data.own||['owner','admin'].includes(team.role)){review.append(button('Show sharing activity',async()=>{const result=await api.action(profile.handle,'activity',{});if(tell(result))review.append(el('pre',result.activity.map(a=>`${a.created_at}: ${a.kind}${a.version?` · version ${a.version}`:''}`).join('\n')||'No activity.'));}),button('Unpublish and remove shared versions',async()=>{if(!window.confirm('Remove all shared versions, receipts and baseline details for this setup?'))return;if(tell(await api.action(profile.handle,'unpublish',{})))await refresh();}));}
  review.scrollIntoView({block:'start'});
}
document.getElementById('refresh').onclick=refresh;api.changed(()=>{draft=null;chosen=null;teams.replaceChildren();review.replaceChildren();status.textContent='Your account changed. Refresh to load current team access.';});void refresh();
