'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const C=require('../../src/borrow/native-codec'),J=require('../../src/borrow/transaction-journal');
const {fixture,snapshot}=require('../helpers/setups-native/runtime');
const helper=process.env.PLEXIFORM_TEST_HELPER;
function memory(){const records=new Map();let created=false;const slot=(r,i,s)=>`${r}:${i}:${s}`;return {records,admit:async()=>{},create:async()=>{assert.equal(created,false);created=true;},write:async(r,i,s,b)=>{const k=slot(r,i,s);assert.equal(records.has(k),false);records.set(k,Buffer.from(b));},sync:async()=>{},read:async(r,i,s)=>{const b=records.get(slot(r,i,s));if(!b)throw Error('Missing');return Buffer.from(b);},inventory:async()=>({entries:[...records].map(([k,b])=>{const [role,index,sequence]=k.split(':').map(Number);return {role,index,sequence,bytes:BigInt(b.length)};})})};}
async function setup(t){const f=fixture(t,helper),metadata=await snapshot(f),before=C.snapshot(metadata);const context={id:randomUUID(),profile:J.hashText(Buffer.from(f.profile)),owner:J.hashText(Buffer.from('owner')),plan:J.hashText(Buffer.from('plan')),source:{profile:randomUUID(),version:randomUUID(),hash:J.hashText(Buffer.from('source'))}},targets=[{file:f.file.id,recipe:'codex-instructions-v1',metadata,before:before.content,base:Buffer.from('Shared synthetic notes.\n'),after:Buffer.from('Write synthetic notes.\n')}],io=memory();return {f,context,targets,io};}
test('whole-selection preparation stores only AEAD records and recovery authenticates every selected snapshot',async t=>{const {f,context,targets,io}=await setup(t);const h=await J.prepareJournal({io,wrapping:f.wrapping,context,targets,current:()=>true});assert.equal(io.records.size,5);for(const b of io.records.values()){assert.equal(b.includes(targets[0].before),false);assert.equal(b.includes(targets[0].after),false);}h.close();const r=await J.recoverJournal({io,wrapping:f.wrapping,id:context.id,profile:context.profile,current:()=>true});const restored=await r.readTarget(0);assert.deepEqual(restored.before,targets[0].before);r.close();});
test('context and role swaps, truncation and ciphertext edits fail authentication',()=>{const key=C.randomBytes(32),context={id:randomUUID(),profile:'1'.repeat(64),owner:'2'.repeat(64),plan:'3'.repeat(64),source:{profile:randomUUID(),version:randomUUID(),hash:'4'.repeat(64)}},plain=Buffer.from('synthetic local private'),sealed=J.seal(key,context,1,0,0,plain);assert.deepEqual(J.open(key,context,1,0,0,sealed),plain);assert.throws(()=>J.open(key,{...context,owner:'5'.repeat(64)},1,0,0,sealed));assert.throws(()=>J.open(key,context,2,0,0,sealed));const bad=Buffer.from(sealed);bad[60]^=1;assert.throws(()=>J.open(key,context,1,0,0,bad));assert.throws(()=>J.open(key,context,1,0,0,sealed.subarray(0,-1)));});
test('substituted OS wrap yielding same key is refused by authenticated provenance',async t=>{const {f,context,targets,io}=await setup(t);let captured;const wrapping={available:()=>true,wrap:b=>{captured=Buffer.from(b);return Buffer.from('original OS wrapper');},unwrap:()=>Buffer.from(captured)};const h=await J.prepareJournal({io,wrapping,context,targets,current:()=>true});h.close();const outer=J.manifestOuter(io.records.get('0:0:0'),context.id),body=new C.Writer(C.LIMITS.receipt-44).blob(Buffer.from(require('../../src/plugins/index-verify').canonical(outer.context)),4096).blob(Buffer.from('substituted wrapper!'),65536).blob(outer.encrypted,C.LIMITS.receipt).finish();io.records.set('0:0:0',Buffer.concat([C.sealedHeader(context.id,0,0,0,body.length),body]));await assert.rejects(J.recoverJournal({io,wrapping,id:context.id,profile:context.profile,current:()=>true}));captured.fill(0);});
test('extra children, missing target records and corrupt metadata fail full recovery',async t=>{const {f,context,targets,io}=await setup(t);const h=await J.prepareJournal({io,wrapping:f.wrapping,context,targets,current:()=>true});h.close();const before=io.records.get('1:0:0');io.records.delete('1:0:0');await assert.rejects(J.recoverJournal({io,wrapping:f.wrapping,id:context.id,profile:context.profile,current:()=>true}));io.records.set('1:0:0',before);io.records.set('1:1:0',before);await assert.rejects(J.recoverJournal({io,wrapping:f.wrapping,id:context.id,profile:context.profile,current:()=>true}));});
test('out-of-order apply/undo and stale authority cannot append journal grants',async t=>{const {f,context,targets,io}=await setup(t);let current=true;const h=await J.prepareJournal({io,wrapping:f.wrapping,context,targets,current:()=>current});await assert.rejects(h.append('apply_intent',0,Buffer.alloc(0)));await assert.rejects(h.append('undone',0,Buffer.alloc(0)));assert.equal(io.records.size,5);current=false;await assert.rejects(h.readTarget(0));h.close();});
test('authority loss during OS wrap never creates a namespace',async t=>{const {f,context,targets,io}=await setup(t);let current=true;f.state.wrapHook=()=>{current=false;};await assert.rejects(J.prepareJournal({io,wrapping:f.wrapping,context,targets,current:()=>current}));assert.equal(io.records.size,0);});
test('owned worker cutoff terminates while OS wrapping ignores completion and creates no IO effects',async t=>{const {context,targets,io}=await setup(t),{createTransactionWorker}=require('../../src/borrow/transaction-worker'),{performance}=require('node:perf_hooks');const worker=createTransactionWorker(),start=performance.now();await assert.rejects(worker.run('prepare',{context,targets},{io,wrapping:{available:()=>true,wrap:()=>new Promise(()=>{})},current:()=>true,cutoff:start+200}));await worker.close().promise;assert.equal(worker.reapPending,false);assert.equal(io.records.size,0);assert.ok(performance.now()-start<1500);});
test('worker transfers copies and never clears retained caller target buffers',async t=>{const {context,targets,io,f}=await setup(t),{createTransactionWorker}=require('../../src/borrow/transaction-worker'),{performance}=require('node:perf_hooks');const worker=createTransactionWorker(),original=Buffer.from(targets[0].before);try{const result=await worker.run('prepare',{context,targets},{io,wrapping:f.wrapping,current:()=>true,cutoff:performance.now()+3000});assert.equal(result.id,context.id);assert.deepEqual(targets[0].before,original);}finally{await worker.close().promise;}});
