import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { communicationRig, taskMessage, receiptOf } from './communication-helpers.js';
import { TTL_MS } from '../../shared/liveness.js';
import { teamSessionDirectory, guardTeamSessionDirectory, TEAM_SESSION_MAX } from '../team-session-directory.js';

const read = (x, user = x.users.amember, team = x.A.team) => x.as(user, 'GET', '/api/team-session-directory', undefined, { 'x-board-team': team });

test('LOCAL PROOF: uninvolved teammates discover current board runs and send exact journaled task messages with truthful receipt stages', async t => {
  const x = await communicationRig(t), { h, sender: a, recipient: b, A } = x;
  assert.ok(!(await x.as(x.users.amember, 'GET', '/api/my-day')).body.agents.some(r => r.card_id === b.run.card_id));
  const listed = await read(x); assert.equal(listed.status, 200, listed.text);
  assert.equal(listed.body.schema, 1); assert.equal(listed.body.message_contract, 'task-inbox');
  assert.equal(listed.body.principal.member_id, A.member);
  const peer = listed.body.sessions.find(s => s.ref === b.run.run_id);
  assert.ok(peer, 'ordinary teammate run must be visible without assignment or dispatch involvement');
  assert.equal(peer.owner.self, false); assert.equal(peer.owner.user_id, b.user.id);
  assert.equal(peer.card.id, b.run.card_id); assert.equal(peer.provider.id, 'codex');
  assert.equal(peer.online, true); assert.equal(peer.canSend, true); assert.equal(peer.input_needed, false);
  assert.deepEqual(Object.keys(peer).sort(), ['ref','owner','board','card','provider','state','online','hb_age_ms','input_needed','canSend'].sort());
  const path = `/api/cards/${peer.card.id}/messages`;
  const body = { ...taskMessage(b), expected_fence: peer.card.fence };
  const sent = await x.as(x.users.amember, 'POST', path, body, { 'x-board-team': A.team });
  assert.equal(sent.status, 200, sent.text); assert.equal(sent.body.message.deliveries[0].state, 'pending');
  assert.equal(sent.body.message.request_id, body.request_id, 'creation receipt binds this exact outbound request');
  assert.equal(sent.body.message.body, body.body);
  assert.equal(sent.body.message.author.account_id, x.users.amember.id);
  assert.equal(sent.body.message.author.identity_source, 'staff_credential');
  assert.equal(sent.body.message.author.member_id, A.member); assert.equal(sent.body.message.auto_resume, false);
  assert.equal(sent.body.message.grants_execution, false);
  assert.equal(h.db.get("SELECT COUNT(*) n FROM journal WHERE kind = 'message.create'").n, 1);
  assert.equal((await x.as(x.users.amember, 'POST', path, body)).body.message.id, sent.body.message.id, 'exact retry stays one journaled message');
  const incoming = (await b.client.rpc(b.run, 'board_list_messages')).result.inbox.find(m => m.id === sent.body.message.id);
  assert.ok(incoming); assert.equal(incoming.body, body.body);
  const receipt = receiptOf(incoming);
  assert.equal((await b.client.rpc(b.run, 'runner_messages_received', { receipts: [receipt] })).ok, true);
  assert.equal((await b.client.rpc(b.run, 'board_ack_message', receipt)).ok, true);
  const history = await x.as(x.users.amember, 'GET', path);
  assert.equal(history.body.messages[0].deliveries[0].state, 'acknowledged');
  assert.equal(history.body.messages[0].deliveries[0].acknowledgement_source, 'agent_reported');
  const reply = await b.client.rpc(b.run, 'board_send_message', taskMessage(a, { body: 'Reviewed exact selected run.', reply_to: sent.body.message.id, thread_id: sent.body.message.thread_id }));
  assert.equal(reply.ok, true, JSON.stringify(reply.error));
  assert.equal((await a.client.rpc(a.run, 'board_list_messages')).result.inbox[0].reply_to, sent.body.message.id);
  const viewer = await read(x, x.users.aviewer); assert.equal(viewer.status, 200, viewer.text);
  assert.ok(viewer.body.sessions.length >= 2); assert.ok(viewer.body.sessions.every(s => s.canSend === false));
  assert.equal((await x.as(x.users.aviewer, 'POST', path, { ...body, request_id: randomUUID() })).status, 403);
  assert.equal((await read(x, x.users.ub)).status, 404, 'foreign user cannot select this team');
  assert.equal((await read(x, x.users.bguest, x.B.team)).status, 404, 'client guest is not staff');
  h.db.run('UPDATE members SET removed_at = ? WHERE id = ?', h.hub.iso(), A.member);
  assert.equal((await read(x)).status, 404);
  assert.notEqual((await x.as(x.users.amember, 'POST', path, { ...body, request_id: randomUUID() })).status, 200);
});

test('team directory strips private fields, binds input to current run and rejects ended, revoked, malformed and unlinked ownership', async t => {
  const x = await communicationRig(t), { h, recipient: b, A } = x;
  h.db.run('UPDATE cards SET title = ?, body = ? WHERE id = ?', 'Human task API_TOKEN=fixtureSecret123 /private/fixture C:\\fixture\\hidden', 'PRIVATE BODY', b.run.card_id);
  h.db.run('UPDATE runs SET session_ids = ?, branch = ? WHERE id = ?', '["private-native-session"]', 'private-branch', b.run.run_id);
  h.db.insert('asks', { id: randomUUID(), card_id: b.run.card_id, run_id: b.run.run_id, kind: 'question', text: 'PRIVATE QUESTION', state: 'open', created_at: h.hub.iso() });
  let response = await read(x), peer = response.body.sessions.find(s => s.ref === b.run.run_id);
  assert.equal(peer.input_needed, true); assert.ok(peer.card.title.startsWith('Human task'));
  for (const forbidden of ['PRIVATE BODY', 'PRIVATE QUESTION', 'private-branch', 'private-native-session', 'fixtureSecret123', '/private/fixture', 'C:\\fixture\\hidden']) assert.ok(!response.text.includes(forbidden), forbidden);
  h.db.run('UPDATE asks SET state = ? WHERE run_id = ?', 'answered', b.run.run_id);
  h.db.insert('asks', { id: randomUUID(), card_id: b.run.card_id, run_id: x.B.run, kind: 'question', text: 'stale question', state: 'open', created_at: h.hub.iso() });
  assert.equal((await read(x)).body.sessions.find(s => s.ref === b.run.run_id).input_needed, false);
  const absent = async () => assert.ok(!(await read(x)).body.sessions.some(s => s.ref === b.run.run_id));
  h.db.run('UPDATE runs SET ended_at = ? WHERE id = ?', h.hub.iso(), b.run.run_id); await absent();
  h.db.run('UPDATE runs SET ended_at = NULL, fence = fence + 1 WHERE id = ?', b.run.run_id); await absent();
  h.db.run('UPDATE runs SET fence = fence - 1 WHERE id = ?', b.run.run_id);
  h.db.run('DELETE FROM board_repos WHERE board_id = ? AND repo_id = ?', A.board, A.repo); await absent();
  h.db.run('INSERT INTO board_repos VALUES (?, ?)', A.board, A.repo);
  const otherRepo = randomUUID(); h.db.insert('repos', { id: otherRepo, org_id: A.team, canonical_url: 'github.com/alpha/other', short_name: 'other' });
  h.db.run('UPDATE runs SET repo_id = ? WHERE id = ?', otherRepo, b.run.run_id); await absent();
  h.db.run('UPDATE runs SET repo_id = ? WHERE id = ?', A.repo, b.run.run_id);
  h.db.run('UPDATE cards SET archived_at = ? WHERE id = ?', h.hub.iso(), b.run.card_id); await absent();
  h.db.run('UPDATE cards SET archived_at = NULL WHERE id = ?', b.run.card_id);
  h.db.run('UPDATE runner_enrollments SET revoked_at = ? WHERE id = ?', h.hub.iso(), b.enrollment); await absent();
  h.db.run('UPDATE runner_enrollments SET revoked_at = NULL WHERE id = ?', b.enrollment);
  h.db.run('UPDATE devices SET revoked_at = ? WHERE id = ?', h.hub.iso(), b.client.welcome.device_id); await absent();
  h.db.run('UPDATE user_devices SET revoked_at = ? WHERE id = ?', h.hub.iso(), x.users.amember.device_id);
  assert.equal((await read(x)).status, 401);
});

test('freshness requires accepted runner, current advertised repository, live child and monotonic heartbeat; listing stays bounded', async t => {
  const x = await communicationRig(t), { h, recipient: b, A } = x;
  const get = async () => (await read(x)).body.sessions.find(s => s.ref === b.run.run_id);
  assert.equal((await get()).canSend, true);
  const lease = h.hub.lease(b.run.run_id), heartbeat = lease.hb_mono;
  lease.hb_mono = h.hub.mono() - TTL_MS - 10;
  assert.equal((await get()).online, false); assert.equal((await get()).canSend, false);
  lease.hb_mono = heartbeat; lease.child_alive = false;
  assert.equal((await get()).online, false);
  lease.child_alive = true;
  const c = b.connection(), advertised = c.repos.get(A.repo); c.repos.delete(A.repo);
  assert.equal((await get()).online, false); c.repos.set(A.repo, advertised);
  c.ready = false; assert.equal((await get()).online, false); c.ready = true;
  assert.equal((await get()).canSend, true);
  const template = h.hub.card(b.run.card_id), run = h.hub.run(b.run.run_id), dispatch = h.db.get('SELECT * FROM dispatches WHERE request_id = ?', run.dispatch_request_id);
  h.hub.txn(() => { for (let i = 0; i < TEAM_SESSION_MAX + 1; i++) {
    const cardId = randomUUID(), runId = randomUUID(), requestId = randomUUID();
    h.db.insert('cards', { ...template, id: cardId, key: `BOUND-${i}`, active_run_id: null });
    h.db.insert('dispatches', { ...dispatch, request_id: requestId, card_id: cardId });
    h.db.insert('runs', { ...run, id: runId, card_id: cardId, dispatch_request_id: requestId });
    h.db.run('UPDATE cards SET active_run_id = ? WHERE id = ?', runId, cardId);
  }});
  const bounded = await read(x); assert.equal(bounded.status, 200, bounded.text);
  assert.equal(bounded.body.status, 'partial'); assert.equal(bounded.body.sessions.length, TEAM_SESSION_MAX);
  assert.throws(() => teamSessionDirectory(h.hub, h.hub.member(A.member)), /staff credential required/);
  assert.throws(() => teamSessionDirectory(h.hub, h.hub.member(A.member), { kind: 'device', id: x.users.ua.device_id }), /credential does not belong/);
});

test('delivery guard rechecks credential and membership and reprojects changed ownership after the HTTP await gap', async t => {
  const x = await communicationRig(t), { h, A, recipient: b } = x;
  const member = h.hub.member(A.member), cred = { kind: 'device', id: x.users.amember.device_id };
  let snapshot = teamSessionDirectory(h.hub, member, cred);
  assert.throws(() => guardTeamSessionDirectory(h.hub, { ...snapshot }), /current team directory/);
  h.db.run('UPDATE runs SET ended_at = ? WHERE id = ?', h.hub.iso(), b.run.run_id);
  guardTeamSessionDirectory(h.hub, snapshot); assert.ok(!snapshot.sessions.some(s => s.ref === b.run.run_id));
  h.db.run('UPDATE runs SET ended_at = NULL WHERE id = ?', b.run.run_id);
  snapshot = teamSessionDirectory(h.hub, member, cred);
  h.db.run("UPDATE members SET role = 'viewer' WHERE id = ?", A.member);
  guardTeamSessionDirectory(h.hub, snapshot); assert.equal(snapshot.principal.role, 'viewer'); assert.ok(snapshot.sessions.every(s => !s.canSend));
  h.db.run("UPDATE members SET role = 'member' WHERE id = ?", A.member);
  const iso = h.hub.iso.bind(h.hub); let revokeDuringRead = true;
  h.hub.iso = () => { const now = iso(); if (revokeDuringRead) { revokeDuringRead = false; queueMicrotask(() => h.db.run('UPDATE user_devices SET revoked_at = ? WHERE id = ?', now, cred.id)); } return now; };
  const refused = await read(x); h.hub.iso = iso;
  assert.equal(refused.status, 401, refused.text); assert.ok(!refused.text.includes(b.run.run_id));
  h.db.run('UPDATE user_devices SET revoked_at = NULL WHERE id = ?', cred.id);
  snapshot = teamSessionDirectory(h.hub, member, cred);
  h.db.run('UPDATE members SET removed_at = ? WHERE id = ?', iso(), A.member);
  assert.throws(() => guardTeamSessionDirectory(h.hub, snapshot), /task context not found/);
});
