import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { communicationRig, receiptOf } from '../../hub/test/communication-helpers.js';

let chromium;
try { ({ chromium } = await import('playwright')); } catch { /* optional runtime */ }

test('actual browser edits durable context, retains conflict drafts and exchanges truthful task messages', { skip: !chromium && 'playwright not installed' }, async (t) => {
  const x = await communicationRig(t, { config: { webDir: fileURLToPath(new URL('../../web', import.meta.url)) } });
  const browser = await chromium.launch({ channel: 'chrome', headless: true }); t.after(() => browser.close());
  const context = await browser.newContext({ baseURL: x.h.base, viewport: { width: 1280, height: 1100 }, extraHTTPHeaders: { Authorization: `Bearer ${x.users.amember.token}` } });
  const page = await context.newPage(), errors = []; page.on('pageerror', (e) => errors.push(e.message)); page.setDefaultTimeout(12000);
  await page.goto(`/?org=${x.A.team}&board=${x.A.board}`);
  await page.click(`.card[data-card-id="${x.sender.run.card_id}"] .card-open`);
  await page.getByRole('tab', { name: 'Task context', exact: true }).click();
  const editor = page.locator('[data-form="task-packet"]'); await editor.waitFor();
  await editor.locator('[name="brief"]').fill('Keep keyboard navigation accessible.');
  await editor.locator('[name="decisions"]').fill('Use the existing route');
  await editor.locator('[name="nextAction"]').fill('Review with the team');
  await editor.locator('[name="paths"]').fill('src/app.js');
  await editor.locator('[name="reportedChecks"]').fill('Focused tests reported passing');
  let reply = page.waitForResponse((r) => r.request().method() === 'POST' && new URL(r.url()).pathname.endsWith('/packet'));
  await editor.getByRole('button', { name: 'Save task context', exact: true }).click();
  let response = await reply; assert.equal(response.status(), 200, await response.text());
  await page.getByText('Version 1 ·', { exact: false }).waitFor();
  const first = (await response.json()).packet; assert.equal(first.author.provider, null); assert.equal(first.reports_verified, false);
  await editor.locator('[name="brief"]').fill('My unsaved conflict draft');
  const external = await x.as(x.users.ua, 'POST', `/api/cards/${x.sender.run.card_id}/packet`, {
    request_id: randomUUID(), expected_version: 1, expected_fence: x.sender.run.fence, data: { ...first.data, brief: 'Newer teammate context' },
  }); assert.equal(external.status, 200, external.text);
  await page.getByRole('button', { name: 'Refresh context', exact: true }).click();
  await page.getByText('Version 2 ·', { exact: false }).waitFor();
  assert.equal(await editor.locator('[name="brief"]').inputValue(), 'My unsaved conflict draft');
  reply = page.waitForResponse((r) => r.request().method() === 'POST' && new URL(r.url()).pathname.endsWith('/packet'));
  await editor.getByRole('button', { name: 'Save task context', exact: true }).click(); response = await reply;
  assert.equal(response.status(), 409); assert.equal((await response.json()).error.code, 'VERSION_CONFLICT');
  await editor.getByRole('alert').waitFor(); assert.equal(await editor.locator('[name="brief"]').inputValue(), 'My unsaved conflict draft');
  await editor.getByRole('button', { name: 'Discard draft and reload', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[name="brief"]')?.value === 'Newer teammate context');
  await page.getByRole('tab', { name: 'Messages', exact: true }).click();
  const composer = page.locator('[data-form="task-message"]'); await composer.waitFor();
  await composer.locator('[name="recipient"]').selectOption(x.recipient.run.run_id);
  await composer.locator('[name="body"]').fill('Please review <script>window.messageInjection=true</script> the caller.');
  reply = page.waitForResponse((r) => r.request().method() === 'POST' && new URL(r.url()).pathname.endsWith('/messages'));
  await composer.getByRole('button', { name: 'Send task message', exact: true }).click(); response = await reply;
  assert.equal(response.status(), 200, await response.text()); const message = (await response.json()).message;
  assert.equal(message.author.provider, null); assert.equal(message.auto_resume, false); assert.equal(message.for_agent, false);
  await page.locator('.task-messages').getByText('Please review', { exact: false }).waitFor();
  assert.equal(await page.evaluate(() => window.messageInjection), undefined);
  assert.equal(x.recipient.client.all('comment.deliver').length, 0);
  const inbox = await x.recipient.client.rpc(x.recipient.run, 'board_list_messages'); const receipt = receiptOf(inbox.result.inbox[0]);
  assert.equal((await x.recipient.client.rpc(x.recipient.run, 'runner_messages_received', { receipts: [receipt] })).ok, true);
  assert.equal((await x.recipient.client.rpc(x.recipient.run, 'board_ack_message', receipt)).ok, true);
  await page.getByRole('button', { name: 'Refresh messages', exact: true }).click();
  await page.getByText('Acknowledged (agent reported)', { exact: false }).waitFor();
  assert.ok(!(await page.textContent('body')).includes(receipt.receipt_token));
  const viewer = await browser.newContext({ baseURL: x.h.base, extraHTTPHeaders: { Authorization: `Bearer ${x.users.aviewer.token}` } });
  const viewerPage = await viewer.newPage(); await viewerPage.goto(`/?org=${x.A.team}&board=${x.A.board}`);
  await viewerPage.click(`.card[data-card-id="${x.sender.run.card_id}"] .card-open`);
  await viewerPage.getByRole('tab', { name: 'Task context', exact: true }).click();
  await viewerPage.getByText('Newer teammate context', { exact: true }).waitFor();
  assert.equal(await viewerPage.locator('[data-form="task-packet"]').count(), 0);
  let resume, observed;
  const held = new Promise((resolve) => { resume = resolve; }), entered = new Promise((resolve) => { observed = resolve; });
  t.after(() => resume());
  const oldPath = `/api/cards/${x.sender.run.card_id}/packet`;
  await page.route(`**${oldPath}`, async (route) => { const result = await route.fetch(); observed(); await held; await route.fulfill({ response: result }); });
  await page.getByRole('button', { name: 'Refresh messages', exact: true }).click(); await entered;
  await page.locator('[data-action="close-drawer"]').click();
  await page.locator('[data-dialog="drawer"]').waitFor({ state: 'detached' });
  await page.click(`.card[data-card-id="${x.recipient.run.card_id}"] .card-open`);
  await page.getByRole('tab', { name: 'Task context', exact: true }).click(); await page.locator('[data-form="task-packet"]').waitFor();
  const released = page.waitForResponse((r) => new URL(r.url()).pathname === oldPath); resume(); await released;
  assert.equal(await page.locator('[data-form="task-packet"] [name="brief"]').inputValue(), '', 'old card response cannot fill a later drawer');
  assert.equal(await page.locator('[data-dialog="drawer"]').getByText('Newer teammate context', { exact: true }).count(), 0);
  if (process.env.COMMUNICATION_SCREENSHOT) await page.screenshot({ path: process.env.COMMUNICATION_SCREENSHOT, fullPage: true });
  assert.deepEqual(errors, []);
});
