'use strict';

// Fixed command builder for Burst's Terminal actions. Nothing a renderer sends
// reaches a script except `kind` and `mode`, and both are matched against
// allow-lists. Paths come from the home directory and are single-quoted.

const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http'); // privacy-flow: burst-keep-awake
const { execFile } = require('node:child_process');

const KINDS = Object.freeze(['install', 'enable', 'off', 'repair', 'update', 'uninstall']);
const MODES = Object.freeze(['base-url', 'transparent']);
const KEEP_AWAKE_MODES = Object.freeze(['off', 'ac', 'always']);
const KEEP_AWAKE_MAX_IDLE = 1440;
const REPO_URL = 'https://github.com/andrewbakercloudscale/claude-burst.git';

const q = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`;

function findCheckout(home) {
  const dir = path.join(home, 'claude-burst');
  const ok = fs.existsSync(path.join(dir, 'install.sh')) && fs.existsSync(path.join(dir, '.git'));
  return { dir, exists: ok };
}

function paths(home) {
  return { bin: path.join(home, '.local', 'bin', 'claude-burst'), off: path.join(home, '.local', 'bin', 'burst-off') };
}

// Returns {body, display} or throws {code}. `display` is the one-line command shown in the consent dialog.
function buildScript(kind, { home, mode = 'base-url', checkout = findCheckout(home) } = {}) {
  if (!KINDS.includes(kind)) throw Object.assign(new Error(`unknown action ${kind}`), { code: 'bad_kind' });
  if (!MODES.includes(mode)) throw Object.assign(new Error(`unknown mode ${mode}`), { code: 'bad_mode' });
  const { bin, off } = paths(home);
  const dir = q(checkout.dir);
  const needs = () => { if (!checkout.exists) throw Object.assign(new Error('no Burst checkout found'), { code: 'no_checkout' }); };
  let steps;
  let display;
  switch (kind) {
    case 'install':
      display = `CLAUDE_BURST_REPO=${checkout.dir} CLAUDE_BURST_MODE=${mode} ./install.sh`;
      steps = [
        ...(checkout.exists ? [] : [`echo "Cloning Claude Burst into ${checkout.dir}"`, `git clone ${q(REPO_URL)} ${dir} || exit 1`]),
        `cd ${dir} || exit 1`,
        `CLAUDE_BURST_REPO=${dir} CLAUDE_BURST_MODE=${mode} ./install.sh`,
      ];
      break;
    case 'enable':
      display = `${bin} enable`;
      steps = [`${q(bin)} enable`];
      break;
    case 'off':
      display = off;
      steps = [`if [[ -x ${q(off)} ]]; then ${q(off)}; else echo "burst-off is not installed (Burst older than v0.11). See ROLLBACK.md in the Burst checkout."; fi`];
      break;
    case 'repair':
      needs();
      display = `CLAUDE_BURST_REPO=${checkout.dir} ${path.join(checkout.dir, 'scripts', 'repair.sh')}`;
      steps = [`cd ${dir} || exit 1`, `CLAUDE_BURST_REPO=${dir} ./scripts/repair.sh`];
      break;
    case 'update':
      needs();
      display = `git pull --ff-only, then CLAUDE_BURST_REPO=${checkout.dir} CLAUDE_BURST_MODE=${mode} CLAUDE_BURST_FORCE=1 ./install.sh`;
      steps = [
        `cd ${dir} || exit 1`,
        'git fetch --tags --quiet origin || exit 1',
        'if git symbolic-ref -q HEAD >/dev/null; then git pull --ff-only --quiet || exit 1; else git -c advice.detachedHead=false checkout --quiet "$(git tag --sort=-v:refname | grep \'^v\' | head -1)" || exit 1; fi',
        `CLAUDE_BURST_REPO=${dir} CLAUDE_BURST_MODE=${mode} CLAUDE_BURST_FORCE=1 ./install.sh`,
      ];
      break;
    case 'uninstall':
      needs();
      display = `${path.join(checkout.dir, 'install.sh')} uninstall`;
      steps = [`cd ${dir} || exit 1`, './install.sh uninstall'];
      break;
  }
  const body = [
    '#!/bin/zsh',
    '# Generated by Plexiform. Rewritten on every click; shown to you before it runs.',
    `echo "== Plexiform: ${kind} (Claude Burst) =="`,
    ...steps,
    'rc=$?',
    'echo',
    'echo "Finished with exit code $rc."',
    '[[ -t 0 ]] && read -k 1 "?Press any key to close this window..."',
    'exit $rc',
    '',
  ].join('\n');
  return { body, display };
}

// `launch` opens Terminal on the file: the same mechanism as Burst's own dashboard.
const launchTerminal = (file) => new Promise((resolve, reject) => {
  execFile('open', ['-a', 'Terminal', file], (err) => (err ? reject(err) : resolve()));
});

async function runInTerminal(kind, { home, mode, dir, launch = launchTerminal, checkout } = {}) {
  const { body, display } = buildScript(kind, { home, mode, checkout });
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  const file = path.join(dir, `burst-${kind}.command`);
  fs.writeFileSync(file, body, { mode: 0o700 });
  fs.chmodSync(file, 0o700);
  await launch(file);
  return { file, display };
}

// The one HTTP mutation here: POST /api/keep-awake to the trusted Burst address (`url` is
// client.adminUrl(), only given once detection passed). Body is exactly {mode, idle_minutes},
// the only fields Burst reads; the admin header is required. Loopback only, nothing else.
function setKeepAwake({ url, mode, idleMinutes = 0, timeoutMs = 20000 } = {}) {
  return new Promise((resolve, reject) => {
    const fail = (code, message, extra) => reject(Object.assign(new Error(message), { code }, extra));
    if (!KEEP_AWAKE_MODES.includes(mode) || !Number.isInteger(idleMinutes) || idleMinutes < 0 || idleMinutes > KEEP_AWAKE_MAX_IDLE) return fail('bad_request', 'bad request');
    let u;
    try { u = new URL(url); } catch { return fail('no_address', 'no trusted address'); }
    if (u.protocol !== 'http:' || (u.hostname !== '127.0.0.1' && u.hostname !== '[::1]')) return fail('no_address', 'no trusted address');
    const body = JSON.stringify({ mode, idle_minutes: idleMinutes });
    const headers = { Host: '127.0.0.1', Accept: 'application/json', 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'X-Claude-Burst-Admin': '1' };
    const req = http.request({ host: u.hostname.replace(/^\[|\]$/g, ''), port: Number(u.port), method: 'POST', path: '/api/keep-awake', headers, agent: false, timeout: timeoutMs }, (res) => { // privacy-flow: burst-keep-awake
      const parts = [];
      let n = 0;
      res.on('data', (c) => { if (n < 4000) { parts.push(c); n += c.length; } });
      res.on('end', () => {
        const text = Buffer.concat(parts).toString('utf8').trim();
        if (res.statusCode !== 200) return fail('http', `http ${res.statusCode}`, { status: res.statusCode, detail: text.slice(0, 300) });
        let j = {};
        try { j = JSON.parse(text); } catch { return fail('bad_json', 'bad json'); }
        resolve({ ok: true, detail: typeof j.detail === 'string' ? j.detail.slice(0, 300) : '', needsPassword: typeof j.script === 'string' });
      });
      res.on('error', () => fail('unreachable', 'unreachable'));
    });
    req.on('timeout', () => { req.destroy(); fail('timeout', 'timeout'); });
    req.on('error', () => fail('unreachable', 'unreachable'));
    req.end(body);
  });
}

module.exports = { buildScript, runInTerminal, findCheckout, setKeepAwake, KINDS, MODES, KEEP_AWAKE_MODES };
